@echo off
setlocal EnableExtensions
cd /d "%~dp0"

if not exist "PowerPointLite.exe" (
  echo PowerPointLite.exe was not found.
  echo Run BUILD_EXE.cmd first.
  if not defined PPLT_NO_PAUSE pause
  exit /b 1
)

echo ==========================================
echo PowerPointLite structural self-tests
echo PPTX / Animation / SVG / Renderer-Fidelity / DOCX / XLSX / HWPX / HWP
echo ODT / ODS / ODP / PDF / Conversion
echo Font licensing / document safety
echo ==========================================
echo.

call :run --writer-selftest "TEST_WRITER_OUTPUT.pptx" "PPTX"
if errorlevel 1 goto :failed

if exist "ANIMATION_SELFTEST_OUTPUT" rmdir /s /q "ANIMATION_SELFTEST_OUTPUT"
mkdir "ANIMATION_SELFTEST_OUTPUT"
echo [RUN] PPTX animation timing
"PowerPointLite.exe" --animation-selftest "%CD%\ANIMATION_SELFTEST_OUTPUT"
if errorlevel 1 (
  echo [FAIL] PPTX animation timing
  goto :failed
)
echo [OK] PPTX animation timing process completed
echo.

echo [RUN] SVG rendering
if exist "TEST_SVG_RENDER.png" del /q "TEST_SVG_RENDER.png"
"PowerPointLite.exe" --svg-selftest "%CD%\TEST_SVG_RENDER.png"
if errorlevel 1 (
  echo [FAIL] SVG rendering
  goto :failed
)
echo [OK] SVG rendering process completed
echo.

if exist "PPTX_FIDELITY_SELFTEST_OUTPUT" rmdir /s /q "PPTX_FIDELITY_SELFTEST_OUTPUT"
mkdir "PPTX_FIDELITY_SELFTEST_OUTPUT"
echo [RUN] PPTX renderer fidelity
"PowerPointLite.exe" --pptx-fidelity-selftest "%CD%\PPTX_FIDELITY_SELFTEST_OUTPUT"
if errorlevel 1 (
  echo [FAIL] PPTX chart / SmartArt fidelity
  goto :failed
)
echo [OK] PPTX chart / SmartArt fidelity process completed
echo.

call :run --docx-selftest "TEST_DOCX_OUTPUT.docx" "DOCX"
if errorlevel 1 goto :failed

call :run --xlsx-selftest "TEST_XLSX_OUTPUT.xlsx" "XLSX"
if errorlevel 1 goto :failed

call :run --hwpx-selftest "TEST_HWPX_OUTPUT.hwpx" "HWPX"
if errorlevel 1 goto :failed

call :run --odt-selftest "TEST_ODT_OUTPUT.odt" "ODT"
if errorlevel 1 goto :failed

call :run --ods-selftest "TEST_ODS_OUTPUT.ods" "ODS"
if errorlevel 1 goto :failed

call :run --odp-selftest "TEST_ODP_OUTPUT.odp" "ODP"
if errorlevel 1 goto :failed

echo [RUN] HWP parser
"PowerPointLite.exe" --hwp-parser-selftest
if errorlevel 1 (
  echo [FAIL] HWP parser
  goto :failed
)
echo [OK] HWP parser process completed
echo.

if exist "PDF_SELFTEST_OUTPUT" rmdir /s /q "PDF_SELFTEST_OUTPUT"
mkdir "PDF_SELFTEST_OUTPUT"
echo [RUN] PDF raster exporter
"PowerPointLite.exe" --pdf-selftest "%CD%\PDF_SELFTEST_OUTPUT"
if errorlevel 1 (
  echo [FAIL] PDF raster exporter
  goto :failed
)
echo [OK] PDF raster exporter process completed
echo.

if exist "CONVERSION_SELFTEST_OUTPUT" rmdir /s /q "CONVERSION_SELFTEST_OUTPUT"
mkdir "CONVERSION_SELFTEST_OUTPUT"
echo [RUN] Cross-format conversion
"PowerPointLite.exe" --conversion-selftest "%CD%\CONVERSION_SELFTEST_OUTPUT"
if errorlevel 1 (
  echo [FAIL] Cross-format conversion
  goto :failed
)
echo [OK] Cross-format conversion process completed
echo.

echo [RUN] Font licensing parser/policy
"PowerPointLite.exe" --font-license-selftest
if errorlevel 1 (
  echo [FAIL] Font licensing parser/policy
  goto :failed
)
echo [OK] Font licensing parser/policy process completed
echo.

if exist "DOCUMENT_SAFETY_SELFTEST_OUTPUT" rmdir /s /q "DOCUMENT_SAFETY_SELFTEST_OUTPUT"
mkdir "DOCUMENT_SAFETY_SELFTEST_OUTPUT"
echo [RUN] Deny-by-default document safety
"PowerPointLite.exe" --document-safety-selftest "%CD%\DOCUMENT_SAFETY_SELFTEST_OUTPUT"
if errorlevel 1 (
  echo [FAIL] Deny-by-default document safety
  goto :failed
)
echo [OK] Deny-by-default document safety process completed
echo.

echo ==========================================
echo ALL STRUCTURAL SELF-TESTS FINISHED
echo ==========================================
echo.
echo Additional manual checks are still required:
echo - PowerPointLite Viewer regression including animation timing
echo - Microsoft PowerPoint / LibreOffice for PPTX
echo - Microsoft Word / LibreOffice for DOCX
echo - Microsoft Excel / LibreOffice for XLSX
echo - Hancom for HWPX
echo - Rights-cleared real HWP 5.x samples for HWP read-only verification
echo - LibreOffice for ODT / ODS / ODP
echo - PDF reader visual inspection and print verification
echo - Actual font license text review before any font-file bundling or embedding
echo.
echo PPTX animation rendering is an internal compatibility approximation; exact PowerPoint effects need manual comparison.
echo PDF export currently rasterizes pages and does not embed source font files.
echo Safety fixtures are generated by this project and contain no third-party document content.
echo.
if not defined PPLT_NO_PAUSE pause
exit /b 0

:run
echo [RUN] %~3
if exist "%~2" del /q "%~2"
"PowerPointLite.exe" %~1 "%CD%\%~2"
if errorlevel 1 (
  echo [FAIL] %~3
  exit /b 1
)
echo [OK] %~3 process completed
echo.
exit /b 0

:failed
echo.
echo ONE OR MORE STRUCTURAL SELF-TESTS FAILED.
if not defined PPLT_NO_PAUSE pause
exit /b 1
