using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Xml;

namespace PptxViewer
{
    internal sealed class DocxEditSafetyResult
    {
        public bool IsProjectGenerated { get; set; }
        public bool HasUnsupportedParts { get; set; }
        public bool CanEditSafely { get; set; }
        public string Warning { get; set; }

        public DocxEditSafetyResult()
        {
            Warning = string.Empty;
        }
    }

    internal static class DocxEditSafety
    {
        public static DocxEditSafetyResult Analyze(string path)
        {
            if (string.IsNullOrEmpty(path) || !File.Exists(path))
                throw new FileNotFoundException("DOCX file was not found.", path);

            DocxEditSafetyResult result = new DocxEditSafetyResult();
            HashSet<string> allowed = new HashSet<string>(
                StringComparer.OrdinalIgnoreCase);

            allowed.Add("[Content_Types].xml");
            allowed.Add("_rels/.rels");
            allowed.Add("docProps/core.xml");
            allowed.Add("docProps/app.xml");
            allowed.Add("word/document.xml");
            allowed.Add("word/styles.xml");
            allowed.Add("word/_rels/document.xml.rels");

            using (ZipArchive archive = ZipFile.OpenRead(path))
            {
                result.IsProjectGenerated = IsProjectGenerated(archive);

                for (int i = 0; i < archive.Entries.Count; i++)
                {
                    string name = archive.Entries[i].FullName.Replace('\\', '/');

                    if (name.EndsWith("/", StringComparison.Ordinal))
                        continue;

                    if (!allowed.Contains(name))
                    {
                        result.HasUnsupportedParts = true;
                        break;
                    }
                }
            }

            result.CanEditSafely =
                result.IsProjectGenerated &&
                !result.HasUnsupportedParts;

            if (!result.CanEditSafely)
            {
                result.Warning = result.IsProjectGenerated
                    ? "This DOCX contains package parts not yet represented by the current document model. It will remain read-only to avoid data loss."
                    : "This DOCX was not generated by the current project writer. Existing arbitrary DOCX editing stays disabled until unsupported-part preservation is implemented.";
            }

            return result;
        }

        private static bool IsProjectGenerated(ZipArchive archive)
        {
            XmlDocument app =
                OpcPackageUtility.ReadXmlPart(archive, "docProps/app.xml");

            if (app == null || app.DocumentElement == null)
                return false;

            XmlNode application = FindFirst(
                app.DocumentElement,
                "Application");

            return application != null &&
                string.Equals(
                    application.InnerText,
                    "PowerPointLite",
                    StringComparison.OrdinalIgnoreCase);
        }

        private static XmlNode FindFirst(XmlNode node, string localName)
        {
            if (node == null)
                return null;

            if (node.LocalName == localName)
                return node;

            for (int i = 0; i < node.ChildNodes.Count; i++)
            {
                XmlNode found = FindFirst(node.ChildNodes[i], localName);
                if (found != null)
                    return found;
            }

            return null;
        }
    }
}
