using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Security;
using System.Text;
using System.Xml;

namespace PptxViewer
{
    internal sealed class HwpxEditSafetyResult
    {
        public bool IsHwpxPackage { get; set; }
        public bool IsProjectGenerated { get; set; }
        public bool HasUnsupportedContent { get; set; }
        public bool CanEditSafely { get; set; }
        public string Warning { get; set; }

        public HwpxEditSafetyResult()
        {
            Warning = string.Empty;
        }
    }

    internal static class HwpxEditSafety
    {
        private const string HwpxMimeType = "application/hwp+zip";

        public static HwpxEditSafetyResult Analyze(string path)
        {
            if (string.IsNullOrEmpty(path) || !File.Exists(path))
                throw new FileNotFoundException("HWPX file was not found.", path);

            HwpxEditSafetyResult result = new HwpxEditSafetyResult();

            using (ZipArchive archive = ZipFile.OpenRead(path))
            {
                result.IsHwpxPackage =
                    string.Equals(
                        ReadTextEntry(archive, "mimetype").Trim(),
                        HwpxMimeType,
                        StringComparison.Ordinal);

                XmlDocument package = LoadXml(archive, "Contents/content.hpf");
                result.IsProjectGenerated = ContainsProjectGenerator(package);

                for (int i = 0; i < archive.Entries.Count; i++)
                {
                    string part = NormalizePart(archive.Entries[i].FullName);

                    if (!IsSupportedPart(part))
                    {
                        result.HasUnsupportedContent = true;
                        break;
                    }
                }

                XmlDocument manifest = LoadXml(archive, "META-INF/manifest.xml");
                if (ContainsEncryptionMetadata(manifest))
                    result.HasUnsupportedContent = true;
            }

            result.CanEditSafely =
                result.IsHwpxPackage &&
                result.IsProjectGenerated &&
                !result.HasUnsupportedContent;

            if (!result.CanEditSafely)
            {
                if (!result.IsHwpxPackage)
                {
                    result.Warning = "The file is not recognized as an HWPX application/hwp+zip package.";
                }
                else if (!result.IsProjectGenerated)
                {
                    result.Warning = "This HWPX was not generated by the current experimental writer. Editing stays disabled until unknown-part preservation is complete.";
                }
                else
                {
                    result.Warning = "This HWPX contains package parts that the experimental writer does not yet preserve. The original file must remain unchanged.";
                }
            }

            return result;
        }

        private static bool IsSupportedPart(string part)
        {
            if (string.IsNullOrEmpty(part))
                return true;

            if (string.Equals(part, "mimetype", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(part, "version.xml", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(part, "META-INF/container.xml", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(part, "META-INF/manifest.xml", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(part, "Contents/content.hpf", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(part, "Contents/header.xml", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(part, "Preview/PrvText.txt", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            if (part.StartsWith("Contents/section", StringComparison.OrdinalIgnoreCase) &&
                part.EndsWith(".xml", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            return false;
        }

        private static bool ContainsProjectGenerator(XmlDocument document)
        {
            if (document == null || document.DocumentElement == null)
                return false;

            XmlNodeList nodes = document.GetElementsByTagName("*");
            for (int i = 0; i < nodes.Count; i++)
            {
                XmlNode node = nodes[i];
                if (node == null)
                    continue;

                if ((node.LocalName == "creator" || node.LocalName == "meta") &&
                    ((node.InnerText ?? string.Empty).IndexOf(
                        "PowerPointLite",
                        StringComparison.OrdinalIgnoreCase) >= 0 ||
                     GetAttribute(node, "content").IndexOf(
                        "PowerPointLite",
                        StringComparison.OrdinalIgnoreCase) >= 0))
                {
                    return true;
                }
            }

            return false;
        }

        private static bool ContainsEncryptionMetadata(XmlDocument manifest)
        {
            if (manifest == null || manifest.DocumentElement == null)
                return false;

            XmlNodeList nodes = manifest.GetElementsByTagName("*");
            for (int i = 0; i < nodes.Count; i++)
            {
                string local = nodes[i] == null ? string.Empty : nodes[i].LocalName;
                if (string.Equals(local, "encryption-data", StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(local, "algorithm", StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(local, "key-derivation", StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }

            return false;
        }

        private static XmlDocument LoadXml(ZipArchive archive, string path)
        {
            ZipArchiveEntry entry = archive.GetEntry(path);
            if (entry == null)
                return null;

            XmlDocument document = new XmlDocument();
            document.PreserveWhitespace = true;
            using (Stream stream = entry.Open())
                document.Load(stream);
            return document;
        }

        private static string ReadTextEntry(ZipArchive archive, string path)
        {
            ZipArchiveEntry entry = archive.GetEntry(path);
            if (entry == null)
                return string.Empty;

            using (Stream stream = entry.Open())
            using (StreamReader reader = new StreamReader(stream, Encoding.UTF8, true))
                return reader.ReadToEnd();
        }

        private static string GetAttribute(XmlNode node, string name)
        {
            if (node == null || node.Attributes == null)
                return string.Empty;

            XmlAttribute attribute = node.Attributes[name];
            return attribute == null ? string.Empty : attribute.Value;
        }

        private static string NormalizePart(string value)
        {
            return (value ?? string.Empty).Replace('\\', '/').TrimStart('/');
        }
    }

    internal static class HwpxReader
    {
        private sealed class CharacterStyle
        {
            public string FontFamily;
            public float SizePoints;
            public bool Bold;
            public bool Italic;
            public bool Underline;
            public string ColorHex;

            public CharacterStyle()
            {
                FontFamily = "Arial";
                SizePoints = 11f;
                ColorHex = "20242A";
            }
        }

        public static TextDocument Read(string path)
        {
            if (string.IsNullOrEmpty(path) || !File.Exists(path))
                throw new FileNotFoundException("HWPX file was not found.", path);

            using (ZipArchive archive = ZipFile.OpenRead(path))
            {
                string mime = ReadTextEntry(archive, "mimetype").Trim();
                if (!string.Equals(mime, "application/hwp+zip", StringComparison.Ordinal))
                    throw new InvalidDataException("The package mimetype is not application/hwp+zip.");

                string packagePart = ReadRootPackagePart(archive);
                XmlDocument package = LoadXml(archive, packagePart);
                if (package == null)
                    throw new InvalidDataException("HWPX package metadata could not be read.");

                TextDocument document = TextDocument.CreateNew(ReadTitle(package));
                Dictionary<string, string> manifest = ReadManifest(package);
                List<string> sectionParts = ReadSpine(package, manifest, packagePart);

                Dictionary<int, string> fonts = new Dictionary<int, string>();
                Dictionary<int, CharacterStyle> charStyles = new Dictionary<int, CharacterStyle>();
                Dictionary<int, DocumentParagraphAlignment> paraStyles =
                    new Dictionary<int, DocumentParagraphAlignment>();

                XmlDocument header = LoadXml(archive, ResolveRelativePart(packagePart, "header.xml"));
                ReadHeaderStyles(header, fonts, charStyles, paraStyles);

                for (int i = 0; i < sectionParts.Count; i++)
                    ReadSection(archive, sectionParts[i], document, charStyles, paraStyles);

                if (document.Paragraphs.Count == 0)
                    document.AddParagraph(string.Empty);

                return document;
            }
        }

        private static void ReadSection(
            ZipArchive archive,
            string part,
            TextDocument document,
            Dictionary<int, CharacterStyle> charStyles,
            Dictionary<int, DocumentParagraphAlignment> paraStyles)
        {
            XmlDocument section = LoadXml(archive, part);
            if (section == null || section.DocumentElement == null)
                return;

            XmlNodeList all = section.GetElementsByTagName("*");
            for (int i = 0; i < all.Count; i++)
            {
                XmlNode paragraphNode = all[i];
                if (paragraphNode == null || paragraphNode.LocalName != "p")
                    continue;

                List<XmlNode> runs = DirectChildren(paragraphNode, "run");
                bool hasText = false;
                for (int r = 0; r < runs.Count && !hasText; r++)
                {
                    hasText = ContainsTextPayload(runs[r]);
                }

                if (!hasText)
                    continue;

                DocumentParagraph paragraph = new DocumentParagraph();
                int paraStyleId = ParseInt(GetAttribute(paragraphNode, "paraPrIDRef"), 0);
                DocumentParagraphAlignment alignment;
                if (paraStyles.TryGetValue(paraStyleId, out alignment))
                    paragraph.Alignment = alignment;

                for (int r = 0; r < runs.Count; r++)
                {
                    XmlNode runNode = runs[r];
                    string text = CollectRunText(runNode);
                    if (text.Length == 0 && !ContainsTextPayload(runNode))
                        continue;

                    DocumentTextRun run = paragraph.AddRun(text);
                    int charStyleId = ParseInt(GetAttribute(runNode, "charPrIDRef"), 0);
                    CharacterStyle style;
                    if (charStyles.TryGetValue(charStyleId, out style))
                    {
                        run.FontFamily = style.FontFamily;
                        run.FontSizePoints = style.SizePoints;
                        run.Bold = style.Bold;
                        run.Italic = style.Italic;
                        run.Underline = style.Underline;
                        run.ColorHex = style.ColorHex;
                    }
                }

                if (paragraph.Runs.Count == 0)
                    paragraph.AddRun(string.Empty);

                document.Paragraphs.Add(paragraph);
            }
        }

        private static void ReadHeaderStyles(
            XmlDocument header,
            Dictionary<int, string> fonts,
            Dictionary<int, CharacterStyle> charStyles,
            Dictionary<int, DocumentParagraphAlignment> paraStyles)
        {
            if (header == null || header.DocumentElement == null)
            {
                charStyles[0] = new CharacterStyle();
                paraStyles[0] = DocumentParagraphAlignment.Left;
                return;
            }

            XmlNodeList nodes = header.GetElementsByTagName("*");

            for (int i = 0; i < nodes.Count; i++)
            {
                XmlNode node = nodes[i];
                if (node == null)
                    continue;

                if (node.LocalName == "font")
                {
                    int id = ParseInt(GetAttribute(node, "id"), -1);
                    string face = GetAttribute(node, "face");
                    if (id >= 0 && !string.IsNullOrEmpty(face) && !fonts.ContainsKey(id))
                        fonts[id] = face;
                }
            }

            for (int i = 0; i < nodes.Count; i++)
            {
                XmlNode node = nodes[i];
                if (node == null)
                    continue;

                if (node.LocalName == "charPr")
                {
                    int id = ParseInt(GetAttribute(node, "id"), -1);
                    if (id < 0)
                        continue;

                    CharacterStyle style = new CharacterStyle();
                    int height = ParseInt(GetAttribute(node, "height"), 1100);
                    style.SizePoints = Math.Max(1f, height / 100f);
                    style.ColorHex = NormalizeColor(GetAttribute(node, "textColor"));

                    XmlNode fontRef = FindChild(node, "fontRef");
                    int fontId = ParseInt(
                        string.IsNullOrEmpty(GetAttribute(fontRef, "hangul"))
                            ? GetAttribute(fontRef, "latin")
                            : GetAttribute(fontRef, "hangul"),
                        0);
                    string family;
                    if (fonts.TryGetValue(fontId, out family))
                        style.FontFamily = family;

                    style.Bold = FindChild(node, "bold") != null;
                    style.Italic = FindChild(node, "italic") != null;
                    XmlNode underline = FindChild(node, "underline");
                    style.Underline = underline != null &&
                        !string.Equals(
                            GetAttribute(underline, "type"),
                            "NONE",
                            StringComparison.OrdinalIgnoreCase);
                    charStyles[id] = style;
                }
                else if (node.LocalName == "paraPr")
                {
                    int id = ParseInt(GetAttribute(node, "id"), -1);
                    if (id < 0)
                        continue;

                    XmlNode align = FindChild(node, "align");
                    string horizontal = GetAttribute(align, "horizontal");
                    paraStyles[id] = ParseAlignment(horizontal);
                }
            }

            if (!charStyles.ContainsKey(0))
                charStyles[0] = new CharacterStyle();
            if (!paraStyles.ContainsKey(0))
                paraStyles[0] = DocumentParagraphAlignment.Left;
        }

        private static string ReadRootPackagePart(ZipArchive archive)
        {
            XmlDocument container = LoadXml(archive, "META-INF/container.xml");
            if (container == null || container.DocumentElement == null)
                return "Contents/content.hpf";

            XmlNodeList nodes = container.GetElementsByTagName("*");
            for (int i = 0; i < nodes.Count; i++)
            {
                XmlNode node = nodes[i];
                if (node == null || node.LocalName != "rootfile")
                    continue;

                if (string.Equals(
                        GetAttribute(node, "media-type"),
                        "application/hwpml-package+xml",
                        StringComparison.OrdinalIgnoreCase))
                {
                    string fullPath = GetAttribute(node, "full-path");
                    if (!string.IsNullOrEmpty(fullPath))
                        return NormalizePart(fullPath);
                }
            }

            return "Contents/content.hpf";
        }

        private static string ReadTitle(XmlDocument package)
        {
            XmlNodeList nodes = package.GetElementsByTagName("*");
            for (int i = 0; i < nodes.Count; i++)
            {
                if (nodes[i] != null && nodes[i].LocalName == "title")
                {
                    string title = nodes[i].InnerText;
                    if (!string.IsNullOrEmpty(title))
                        return title;
                }
            }
            return "HWPX Document";
        }

        private static Dictionary<string, string> ReadManifest(XmlDocument package)
        {
            Dictionary<string, string> result =
                new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            XmlNodeList nodes = package.GetElementsByTagName("*");

            for (int i = 0; i < nodes.Count; i++)
            {
                XmlNode node = nodes[i];
                if (node == null || node.LocalName != "item")
                    continue;

                string id = GetAttribute(node, "id");
                string href = GetAttribute(node, "href");
                if (!string.IsNullOrEmpty(id) && !string.IsNullOrEmpty(href))
                    result[id] = href;
            }

            return result;
        }

        private static List<string> ReadSpine(
            XmlDocument package,
            Dictionary<string, string> manifest,
            string packagePart)
        {
            List<string> result = new List<string>();
            XmlNodeList nodes = package.GetElementsByTagName("*");

            for (int i = 0; i < nodes.Count; i++)
            {
                XmlNode node = nodes[i];
                if (node == null || node.LocalName != "itemref")
                    continue;

                string idRef = GetAttribute(node, "idref");
                string href;
                if (manifest.TryGetValue(idRef, out href))
                {
                    string part = ResolveRelativePart(packagePart, href);
                    if (!result.Contains(part))
                        result.Add(part);
                }
            }

            if (result.Count == 0)
                result.Add(ResolveRelativePart(packagePart, "section0.xml"));
            return result;
        }

        private static string CollectRunText(XmlNode run)
        {
            StringBuilder result = new StringBuilder();
            if (run == null)
                return string.Empty;

            XmlNodeList descendants = run.SelectNodes(".//*");
            if (descendants == null)
                return string.Empty;

            for (int i = 0; i < descendants.Count; i++)
            {
                XmlNode node = descendants[i];
                if (node == null)
                    continue;
                if (node.LocalName == "t")
                    result.Append(node.InnerText ?? string.Empty);
                else if (node.LocalName == "tab")
                    result.Append('\t');
                else if (node.LocalName == "lineBreak")
                    result.Append('\n');
            }
            return result.ToString();
        }

        private static bool ContainsTextPayload(XmlNode run)
        {
            if (run == null)
                return false;
            XmlNodeList descendants = run.SelectNodes(".//*");
            if (descendants == null)
                return false;
            for (int i = 0; i < descendants.Count; i++)
            {
                string local = descendants[i] == null ? string.Empty : descendants[i].LocalName;
                if (local == "t" || local == "tab" || local == "lineBreak")
                    return true;
            }
            return false;
        }

        private static List<XmlNode> DirectChildren(XmlNode parent, string localName)
        {
            List<XmlNode> result = new List<XmlNode>();
            if (parent == null)
                return result;
            for (int i = 0; i < parent.ChildNodes.Count; i++)
            {
                XmlNode child = parent.ChildNodes[i];
                if (child != null && child.LocalName == localName)
                    result.Add(child);
            }
            return result;
        }

        private static XmlNode FindChild(XmlNode parent, string localName)
        {
            if (parent == null)
                return null;
            for (int i = 0; i < parent.ChildNodes.Count; i++)
            {
                XmlNode child = parent.ChildNodes[i];
                if (child != null && child.LocalName == localName)
                    return child;
            }
            return null;
        }

        private static DocumentParagraphAlignment ParseAlignment(string value)
        {
            if (string.Equals(value, "CENTER", StringComparison.OrdinalIgnoreCase))
                return DocumentParagraphAlignment.Center;
            if (string.Equals(value, "RIGHT", StringComparison.OrdinalIgnoreCase))
                return DocumentParagraphAlignment.Right;
            if (string.Equals(value, "JUSTIFY", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(value, "DISTRIBUTE", StringComparison.OrdinalIgnoreCase))
                return DocumentParagraphAlignment.Justify;
            return DocumentParagraphAlignment.Left;
        }

        private static string NormalizeColor(string value)
        {
            string text = (value ?? string.Empty).Trim().TrimStart('#').ToUpperInvariant();
            int parsed;
            if (text.Length == 6 && int.TryParse(text, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out parsed))
                return text;
            return "20242A";
        }

        private static int ParseInt(string value, int fallback)
        {
            int parsed;
            return int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out parsed)
                ? parsed
                : fallback;
        }

        private static string ResolveRelativePart(string sourcePart, string target)
        {
            sourcePart = NormalizePart(sourcePart);
            target = (target ?? string.Empty).Replace('\\', '/');
            int slash = sourcePart.LastIndexOf('/');
            string directory = slash >= 0 ? sourcePart.Substring(0, slash + 1) : string.Empty;
            return OpcPackageUtility.NormalizePartName(directory + target);
        }

        private static XmlDocument LoadXml(ZipArchive archive, string path)
        {
            ZipArchiveEntry entry = archive.GetEntry(NormalizePart(path));
            if (entry == null)
                return null;
            XmlDocument document = new XmlDocument();
            document.PreserveWhitespace = true;
            using (Stream stream = entry.Open())
                document.Load(stream);
            return document;
        }

        private static string ReadTextEntry(ZipArchive archive, string path)
        {
            ZipArchiveEntry entry = archive.GetEntry(NormalizePart(path));
            if (entry == null)
                return string.Empty;
            using (Stream stream = entry.Open())
            using (StreamReader reader = new StreamReader(stream, Encoding.UTF8, true))
                return reader.ReadToEnd();
        }

        private static string GetAttribute(XmlNode node, string name)
        {
            if (node == null || node.Attributes == null)
                return string.Empty;
            XmlAttribute attribute = node.Attributes[name];
            return attribute == null ? string.Empty : attribute.Value;
        }

        private static string NormalizePart(string value)
        {
            return (value ?? string.Empty).Replace('\\', '/').TrimStart('/');
        }
    }

    internal static class HwpxWriter
    {
        private sealed class CharStyleKey
        {
            public string FontFamily;
            public int Height;
            public bool Bold;
            public bool Italic;
            public bool Underline;
            public string Color;

            public string Key
            {
                get
                {
                    return (FontFamily ?? string.Empty) + "|" + Height.ToString(CultureInfo.InvariantCulture) + "|" +
                        (Bold ? "1" : "0") + (Italic ? "1" : "0") + (Underline ? "1" : "0") + "|" + Color;
                }
            }
        }

        private sealed class StyleCatalog
        {
            public readonly List<string> Fonts = new List<string>();
            public readonly Dictionary<string, int> FontIds = new Dictionary<string, int>(StringComparer.CurrentCultureIgnoreCase);
            public readonly List<CharStyleKey> CharStyles = new List<CharStyleKey>();
            public readonly Dictionary<string, int> CharStyleIds = new Dictionary<string, int>(StringComparer.Ordinal);
        }

        public static void Save(TextDocument document, string path)
        {
            if (document == null)
                throw new ArgumentNullException("document");
            if (string.IsNullOrEmpty(path))
                throw new ArgumentException("Destination path is required.", "path");

            string destination = Path.GetFullPath(path);
            if (!string.Equals(Path.GetExtension(destination), ".hwpx", StringComparison.OrdinalIgnoreCase))
                destination += ".hwpx";

            string directory = Path.GetDirectoryName(destination);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);

            string stage = destination + ".writing";
            string backup = destination + ".backup";
            DeleteIfExists(stage);
            DeleteIfExists(backup);

            StyleCatalog styles = BuildStyleCatalog(document);

            try
            {
                using (FileStream file = new FileStream(stage, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.None))
                using (ZipArchive archive = new ZipArchive(file, ZipArchiveMode.Create, false))
                {
                    WriteEntry(archive, "mimetype", "application/hwp+zip", CompressionLevel.NoCompression);
                    WriteEntry(archive, "version.xml", BuildVersionXml(), CompressionLevel.NoCompression);
                    WriteEntry(archive, "META-INF/container.xml", BuildContainerXml(), CompressionLevel.Optimal);
                    WriteEntry(archive, "META-INF/manifest.xml", BuildManifestXml(), CompressionLevel.Optimal);
                    WriteEntry(archive, "Contents/content.hpf", BuildContentXml(document), CompressionLevel.Optimal);
                    WriteEntry(archive, "Contents/header.xml", BuildHeaderXml(styles), CompressionLevel.Optimal);
                    WriteEntry(archive, "Contents/section0.xml", BuildSectionXml(document, styles), CompressionLevel.Optimal);
                    WriteEntry(archive, "Preview/PrvText.txt", BuildPreviewText(document), CompressionLevel.Optimal);
                }

                ReplaceSafely(stage, destination, backup);
            }
            catch
            {
                DeleteIfExists(stage);
                throw;
            }
        }

        private static StyleCatalog BuildStyleCatalog(TextDocument document)
        {
            StyleCatalog catalog = new StyleCatalog();
            AddFont(catalog, "Arial");

            for (int p = 0; p < document.Paragraphs.Count; p++)
            {
                DocumentParagraph paragraph = document.Paragraphs[p];
                if (paragraph == null)
                    continue;

                for (int r = 0; r < paragraph.Runs.Count; r++)
                {
                    DocumentTextRun run = paragraph.Runs[r];
                    if (run == null)
                        continue;
                    string family = string.IsNullOrEmpty(run.FontFamily) ? "Arial" : run.FontFamily;
                    AddFont(catalog, family);

                    CharStyleKey style = CreateStyle(run, family);
                    if (!catalog.CharStyleIds.ContainsKey(style.Key))
                    {
                        int id = catalog.CharStyles.Count;
                        catalog.CharStyleIds.Add(style.Key, id);
                        catalog.CharStyles.Add(style);
                    }
                }
            }

            if (catalog.CharStyles.Count == 0)
            {
                DocumentTextRun fallback = new DocumentTextRun();
                CharStyleKey style = CreateStyle(fallback, "Arial");
                catalog.CharStyleIds.Add(style.Key, 0);
                catalog.CharStyles.Add(style);
            }

            return catalog;
        }

        private static CharStyleKey CreateStyle(DocumentTextRun run, string family)
        {
            CharStyleKey style = new CharStyleKey();
            style.FontFamily = family;
            style.Height = Math.Max(100, Math.Min(40000, (int)Math.Round(run.FontSizePoints * 100.0f)));
            style.Bold = run.Bold;
            style.Italic = run.Italic;
            style.Underline = run.Underline;
            style.Color = NormalizeColor(run.ColorHex);
            return style;
        }

        private static void AddFont(StyleCatalog catalog, string family)
        {
            if (catalog.FontIds.ContainsKey(family))
                return;
            int id = catalog.Fonts.Count;
            catalog.FontIds.Add(family, id);
            catalog.Fonts.Add(family);
        }

        private static string BuildVersionXml()
        {
            return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<hv:HCFVersion xmlns:hv=\"http://www.hancom.co.kr/hwpml/2011/version\" " +
                "tagetApplication=\"WORDPROCESSOR\" major=\"5\" minor=\"1\" micro=\"0\" buildNumber=\"0\"/>";
        }

        private static string BuildContainerXml()
        {
            return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<container version=\"1.0\" xmlns=\"urn:oasis:names:tc:opendocument:xmlns:container\">" +
                "<rootfiles>" +
                "<rootfile full-path=\"Contents/content.hpf\" media-type=\"application/hwpml-package+xml\"/>" +
                "<rootfile full-path=\"Preview/PrvText.txt\" media-type=\"text/plain\"/>" +
                "</rootfiles></container>";
        }

        private static string BuildManifestXml()
        {
            return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<manifest:manifest xmlns:manifest=\"urn:oasis:names:tc:opendocument:xmlns:manifest:1.0\">" +
                ManifestEntry("/", "application/hwp+zip") +
                ManifestEntry("version.xml", "application/xml") +
                ManifestEntry("Contents/content.hpf", "application/hwpml-package+xml") +
                ManifestEntry("Contents/header.xml", "application/xml") +
                ManifestEntry("Contents/section0.xml", "application/xml") +
                ManifestEntry("Preview/PrvText.txt", "text/plain") +
                "</manifest:manifest>";
        }

        private static string ManifestEntry(string path, string mediaType)
        {
            return "<manifest:file-entry manifest:full-path=\"" + Escape(path) +
                "\" manifest:media-type=\"" + Escape(mediaType) + "\"/>";
        }

        private static string BuildContentXml(TextDocument document)
        {
            string title = Escape(string.IsNullOrEmpty(document.Title) ? "New HWPX Document" : document.Title);
            return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<opf:package xmlns:opf=\"http://www.idpf.org/2007/opf/\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" version=\"1.0\" unique-identifier=\"PowerPointLite-HWPX\">" +
                "<opf:metadata><dc:title>" + title + "</dc:title><dc:creator>PowerPointLite</dc:creator>" +
                "<opf:meta name=\"generator\" content=\"PowerPointLite clean-room HWPX writer\"/></opf:metadata>" +
                "<opf:manifest>" +
                "<opf:item id=\"header\" href=\"header.xml\" media-type=\"application/xml\"/>" +
                "<opf:item id=\"section0\" href=\"section0.xml\" media-type=\"application/xml\"/>" +
                "</opf:manifest><opf:spine><opf:itemref idref=\"section0\"/></opf:spine></opf:package>";
        }

        private static string BuildHeaderXml(StyleCatalog catalog)
        {
            StringBuilder xml = new StringBuilder();
            xml.Append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
            xml.Append("<hh:head xmlns:hh=\"http://www.hancom.co.kr/hwpml/2011/head\" xmlns:hc=\"http://www.hancom.co.kr/hwpml/2011/core\" version=\"1.5\" secCnt=\"1\">");
            xml.Append("<hh:refList>");
            xml.Append("<hh:fontfaces itemCnt=\"");
            xml.Append((catalog.Fonts.Count * 7).ToString(CultureInfo.InvariantCulture));
            xml.Append("\">");

            string[] languages = new string[] { "HANGUL", "LATIN", "HANJA", "JAPANESE", "OTHER", "SYMBOL", "USER" };
            for (int lang = 0; lang < languages.Length; lang++)
            {
                xml.Append("<hh:fontface lang=\"");
                xml.Append(languages[lang]);
                xml.Append("\" fontCnt=\"");
                xml.Append(catalog.Fonts.Count.ToString(CultureInfo.InvariantCulture));
                xml.Append("\">");
                for (int i = 0; i < catalog.Fonts.Count; i++)
                {
                    xml.Append("<hh:font id=\"");
                    xml.Append(i.ToString(CultureInfo.InvariantCulture));
                    xml.Append("\" face=\"");
                    xml.Append(Escape(catalog.Fonts[i]));
                    xml.Append("\" type=\"TTF\" isEmbedded=\"0\"/>");
                }
                xml.Append("</hh:fontface>");
            }
            xml.Append("</hh:fontfaces>");

            xml.Append("<hh:charProperties itemCnt=\"");
            xml.Append(catalog.CharStyles.Count.ToString(CultureInfo.InvariantCulture));
            xml.Append("\">");
            for (int i = 0; i < catalog.CharStyles.Count; i++)
                xml.Append(BuildCharPrXml(catalog, catalog.CharStyles[i], i));
            xml.Append("</hh:charProperties>");

            xml.Append("<hh:paraProperties itemCnt=\"4\">");
            xml.Append(BuildParaPrXml(0, "LEFT"));
            xml.Append(BuildParaPrXml(1, "CENTER"));
            xml.Append(BuildParaPrXml(2, "RIGHT"));
            xml.Append(BuildParaPrXml(3, "JUSTIFY"));
            xml.Append("</hh:paraProperties>");
            xml.Append("<hh:styles itemCnt=\"1\"><hh:style id=\"0\" type=\"PARA\" name=\"Normal\" engName=\"Normal\" paraPrIDRef=\"0\" charPrIDRef=\"0\" nextStyleIDRef=\"0\" langID=\"1042\" lockForm=\"0\"/></hh:styles>");
            xml.Append("</hh:refList></hh:head>");
            return xml.ToString();
        }

        private static string BuildCharPrXml(StyleCatalog catalog, CharStyleKey style, int id)
        {
            int fontId;
            if (!catalog.FontIds.TryGetValue(style.FontFamily, out fontId))
                fontId = 0;

            StringBuilder xml = new StringBuilder();
            xml.Append("<hh:charPr id=\"");
            xml.Append(id.ToString(CultureInfo.InvariantCulture));
            xml.Append("\" height=\"");
            xml.Append(style.Height.ToString(CultureInfo.InvariantCulture));
            xml.Append("\" textColor=\"#");
            xml.Append(style.Color);
            xml.Append("\" shadeColor=\"none\" useFontSpace=\"0\" useKerning=\"0\" symMark=\"NONE\" borderFillIDRef=\"0\">");
            xml.Append("<hh:fontRef hangul=\"");
            xml.Append(fontId.ToString(CultureInfo.InvariantCulture));
            xml.Append("\" latin=\"");
            xml.Append(fontId.ToString(CultureInfo.InvariantCulture));
            xml.Append("\" hanja=\"");
            xml.Append(fontId.ToString(CultureInfo.InvariantCulture));
            xml.Append("\" japanese=\"");
            xml.Append(fontId.ToString(CultureInfo.InvariantCulture));
            xml.Append("\" other=\"");
            xml.Append(fontId.ToString(CultureInfo.InvariantCulture));
            xml.Append("\" symbol=\"");
            xml.Append(fontId.ToString(CultureInfo.InvariantCulture));
            xml.Append("\" user=\"");
            xml.Append(fontId.ToString(CultureInfo.InvariantCulture));
            xml.Append("\"/>");
            xml.Append("<hh:ratio hangul=\"100\" latin=\"100\" hanja=\"100\" japanese=\"100\" other=\"100\" symbol=\"100\" user=\"100\"/>");
            xml.Append("<hh:spacing hangul=\"0\" latin=\"0\" hanja=\"0\" japanese=\"0\" other=\"0\" symbol=\"0\" user=\"0\"/>");
            xml.Append("<hh:relSz hangul=\"100\" latin=\"100\" hanja=\"100\" japanese=\"100\" other=\"100\" symbol=\"100\" user=\"100\"/>");
            xml.Append("<hh:offset hangul=\"0\" latin=\"0\" hanja=\"0\" japanese=\"0\" other=\"0\" symbol=\"0\" user=\"0\"/>");
            if (style.Bold)
                xml.Append("<hh:bold/>");
            if (style.Italic)
                xml.Append("<hh:italic/>");
            xml.Append("<hh:underline type=\"");
            xml.Append(style.Underline ? "BOTTOM" : "NONE");
            xml.Append("\" shape=\"SOLID\" color=\"#");
            xml.Append(style.Color);
            xml.Append("\"/>");
            xml.Append("</hh:charPr>");
            return xml.ToString();
        }

        private static string BuildParaPrXml(int id, string horizontal)
        {
            return "<hh:paraPr id=\"" + id.ToString(CultureInfo.InvariantCulture) +
                "\" tabPrIDRef=\"0\" condense=\"0\" fontLineHeight=\"0\" snapToGrid=\"1\" suppressLineNumbers=\"0\" checked=\"0\">" +
                "<hh:align horizontal=\"" + horizontal + "\" vertical=\"BASELINE\"/>" +
                "<hh:heading type=\"NONE\" idRef=\"0\" level=\"0\"/>" +
                "<hh:breakSetting breakLatinWord=\"KEEP_WORD\" breakNonLatinWord=\"KEEP_WORD\" widowOrphan=\"0\" keepWithNext=\"0\" keepLines=\"0\" pageBreakBefore=\"0\" lineWrap=\"BREAK\"/>" +
                "<hh:autoSpacing eAsianEng=\"0\" eAsianNum=\"0\"/>" +
                "</hh:paraPr>";
        }

        private static string BuildSectionXml(TextDocument document, StyleCatalog catalog)
        {
            StringBuilder xml = new StringBuilder();
            xml.Append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
            xml.Append("<hs:sec xmlns:hp=\"http://www.hancom.co.kr/hwpml/2011/paragraph\" xmlns:hs=\"http://www.hancom.co.kr/hwpml/2011/section\">");
            xml.Append(BuildSectionPropertyParagraph());

            int paragraphId = 1000000002;
            for (int p = 0; p < document.Paragraphs.Count; p++)
            {
                DocumentParagraph paragraph = document.Paragraphs[p];
                if (paragraph == null)
                    continue;

                xml.Append("<hp:p id=\"");
                xml.Append(paragraphId.ToString(CultureInfo.InvariantCulture));
                paragraphId++;
                xml.Append("\" paraPrIDRef=\"");
                xml.Append(((int)paragraph.Alignment).ToString(CultureInfo.InvariantCulture));
                xml.Append("\" styleIDRef=\"0\" pageBreak=\"0\" columnBreak=\"0\" merged=\"0\">");

                if (paragraph.Runs.Count == 0)
                {
                    xml.Append("<hp:run charPrIDRef=\"0\"><hp:t/></hp:run>");
                }
                else
                {
                    for (int r = 0; r < paragraph.Runs.Count; r++)
                    {
                        DocumentTextRun run = paragraph.Runs[r];
                        if (run == null)
                            continue;
                        string family = string.IsNullOrEmpty(run.FontFamily) ? "Arial" : run.FontFamily;
                        CharStyleKey style = CreateStyle(run, family);
                        int styleId;
                        if (!catalog.CharStyleIds.TryGetValue(style.Key, out styleId))
                            styleId = 0;

                        xml.Append("<hp:run charPrIDRef=\"");
                        xml.Append(styleId.ToString(CultureInfo.InvariantCulture));
                        xml.Append("\">");
                        AppendTextPayload(xml, run.Text ?? string.Empty);
                        xml.Append("</hp:run>");
                    }
                }

                xml.Append("</hp:p>");
            }

            if (document.Paragraphs.Count == 0)
                xml.Append("<hp:p id=\"1000000002\" paraPrIDRef=\"0\" styleIDRef=\"0\" pageBreak=\"0\" columnBreak=\"0\" merged=\"0\"><hp:run charPrIDRef=\"0\"><hp:t/></hp:run></hp:p>");

            xml.Append("</hs:sec>");
            return xml.ToString();
        }

        private static string BuildSectionPropertyParagraph()
        {
            return "<hp:p id=\"1000000001\" paraPrIDRef=\"0\" styleIDRef=\"0\" pageBreak=\"0\" columnBreak=\"0\" merged=\"0\">" +
                "<hp:run charPrIDRef=\"0\">" +
                "<hp:secPr id=\"\" textDirection=\"HORIZONTAL\" spaceColumns=\"1134\" tabStop=\"8000\" tabStopVal=\"4000\" tabStopUnit=\"HWPUNIT\" outlineShapeIDRef=\"1\" memoShapeIDRef=\"0\" textVerticalWidthHead=\"0\" masterPageCnt=\"0\">" +
                "<hp:grid lineGrid=\"0\" charGrid=\"0\" wonggojiFormat=\"0\"/>" +
                "<hp:startNum pageStartsOn=\"BOTH\" page=\"0\" pic=\"0\" tbl=\"0\" equation=\"0\"/>" +
                "<hp:visibility hideFirstHeader=\"0\" hideFirstFooter=\"0\" hideFirstMasterPage=\"0\" border=\"SHOW_ALL\" fill=\"SHOW_ALL\" hideFirstPageNum=\"0\" hideFirstEmptyLine=\"0\" showLineNumber=\"0\"/>" +
                "<hp:lineNumberShape restartType=\"0\" countBy=\"0\" distance=\"0\" startNumber=\"0\"/>" +
                "<hp:pagePr landscape=\"WIDELY\" width=\"59528\" height=\"84186\" gutterType=\"LEFT_ONLY\"><hp:margin header=\"4252\" footer=\"4252\" gutter=\"0\" left=\"8504\" right=\"8504\" top=\"5668\" bottom=\"4252\"/></hp:pagePr>" +
                "</hp:secPr>" +
                "<hp:ctrl><hp:colPr id=\"\" type=\"NEWSPAPER\" layout=\"LEFT\" colCount=\"1\" sameSz=\"1\" sameGap=\"0\"/></hp:ctrl>" +
                "</hp:run></hp:p>";
        }

        private static void AppendTextPayload(StringBuilder xml, string text)
        {
            string normalized = (text ?? string.Empty).Replace("\r\n", "\n").Replace('\r', '\n');
            if (normalized.Length == 0)
            {
                xml.Append("<hp:t/>");
                return;
            }

            StringBuilder chunk = new StringBuilder();
            for (int i = 0; i < normalized.Length; i++)
            {
                char ch = normalized[i];
                if (ch == '\n' || ch == '\t')
                {
                    if (chunk.Length > 0)
                    {
                        xml.Append("<hp:t>");
                        xml.Append(Escape(chunk.ToString()));
                        xml.Append("</hp:t>");
                        chunk.Length = 0;
                    }
                    xml.Append(ch == '\n' ? "<hp:lineBreak/>" : "<hp:tab/>");
                }
                else
                {
                    chunk.Append(ch);
                }
            }

            if (chunk.Length > 0)
            {
                xml.Append("<hp:t>");
                xml.Append(Escape(chunk.ToString()));
                xml.Append("</hp:t>");
            }
        }

        private static string BuildPreviewText(TextDocument document)
        {
            StringBuilder text = new StringBuilder();
            for (int p = 0; p < document.Paragraphs.Count; p++)
            {
                if (p > 0)
                    text.AppendLine();
                DocumentParagraph paragraph = document.Paragraphs[p];
                if (paragraph != null)
                    text.Append(paragraph.PlainText ?? string.Empty);
            }
            return text.ToString();
        }

        private static void WriteEntry(
            ZipArchive archive,
            string path,
            string content,
            CompressionLevel compression)
        {
            ZipArchiveEntry entry = archive.CreateEntry(path, compression);
            using (Stream stream = entry.Open())
            using (StreamWriter writer = new StreamWriter(stream, new UTF8Encoding(false)))
                writer.Write(content ?? string.Empty);
        }

        private static void ReplaceSafely(string stage, string destination, string backup)
        {
            if (!File.Exists(destination))
            {
                File.Move(stage, destination);
                return;
            }

            File.Move(destination, backup);
            try
            {
                File.Move(stage, destination);
                DeleteIfExists(backup);
            }
            catch
            {
                try
                {
                    DeleteIfExists(destination);
                    if (File.Exists(backup))
                        File.Move(backup, destination);
                }
                catch { }
                throw;
            }
        }

        private static void DeleteIfExists(string path)
        {
            try
            {
                if (File.Exists(path))
                    File.Delete(path);
            }
            catch { }
        }

        private static string NormalizeColor(string value)
        {
            string text = (value ?? string.Empty).Trim().TrimStart('#').ToUpperInvariant();
            int parsed;
            if (text.Length == 6 && int.TryParse(text, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out parsed))
                return text;
            return "20242A";
        }

        private static string Escape(string value)
        {
            return SecurityElement.Escape(value ?? string.Empty) ?? string.Empty;
        }
    }
}
