using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Text;
using System.Xml;

namespace PptxViewer
{
    internal sealed class OdpEditSafetyResult
    {
        public bool IsOdpPackage { get; set; }
        public bool IsProjectGenerated { get; set; }
        public bool HasUnsupportedContent { get; set; }
        public bool CanEditSafely { get; set; }
        public string Warning { get; set; }

        public OdpEditSafetyResult()
        {
            Warning = string.Empty;
        }
    }

    internal static class OdpEditSafety
    {
        public static OdpEditSafetyResult Analyze(string path)
        {
            if (string.IsNullOrEmpty(path) || !File.Exists(path))
                throw new FileNotFoundException("ODP file was not found.", path);

            OdpEditSafetyResult result = new OdpEditSafetyResult();

            using (ZipArchive archive = ZipFile.OpenRead(path))
            {
                result.IsOdpPackage = string.Equals(
                    OdfPackageUtility.ReadTextEntry(archive, "mimetype").Trim(),
                    OdfPackageUtility.PresentationMimeType,
                    StringComparison.Ordinal);
                result.IsProjectGenerated = OdfPackageUtility.IsProjectGenerated(archive);

                List<string> allowed = new List<string>();
                allowed.Add("mimetype");
                allowed.Add("content.xml");
                allowed.Add("styles.xml");
                allowed.Add("meta.xml");
                allowed.Add("META-INF/manifest.xml");
                allowed.Add("Pictures/");
                result.HasUnsupportedContent =
                    !OdfPackageUtility.ContainsOnlyKnownParts(archive, allowed);
            }

            result.CanEditSafely =
                result.IsOdpPackage &&
                result.IsProjectGenerated &&
                !result.HasUnsupportedContent;

            if (!result.CanEditSafely)
            {
                if (!result.IsOdpPackage)
                    result.Warning = "The file is not recognized as an ODP package.";
                else if (!result.IsProjectGenerated)
                    result.Warning = "This ODP was not generated by the current experimental writer. Editing is disabled until preservation support is broader.";
                else
                    result.Warning = "This ODP contains package content that the current model does not preserve.";
            }

            return result;
        }
    }

    internal static class OdpReader
    {
        private sealed class TextStyle
        {
            public string FontFamily = "Arial";
            public float FontSize = 20f;
            public bool Bold;
            public bool Italic;
            public string Color = "20242A";
            public PresentationTextAlignment Alignment = PresentationTextAlignment.Left;
        }

        public static PresentationDocument Read(string path)
        {
            if (!OdfPackageUtility.HasExpectedMimeType(path, OdfDocumentKind.Presentation))
                throw new InvalidDataException("The package mimetype is not ODP.");

            using (ZipArchive archive = ZipFile.OpenRead(path))
            {
                XmlDocument content = OdfPackageUtility.LoadXml(archive, "content.xml");
                if (content == null || content.DocumentElement == null)
                    throw new InvalidDataException("ODP content.xml is missing.");

                Dictionary<string, TextStyle> textStyles = ReadTextStyles(content);
                PresentationDocument document = new PresentationDocument();
                document.Title = ReadTitle(archive);

                XmlNode presentation = FindFirst(content, "presentation");
                if (presentation == null)
                    throw new InvalidDataException("ODP office:presentation body is missing.");

                for (int i = 0; i < presentation.ChildNodes.Count; i++)
                {
                    XmlNode page = presentation.ChildNodes[i];
                    if (page == null || page.LocalName != "page")
                        continue;

                    PresentationSlide slide = new PresentationSlide();
                    string pageName = OdfPackageUtility.GetAttributeByLocalName(page, "name");
                    slide.Name = string.IsNullOrEmpty(pageName)
                        ? "Slide " + (document.Slides.Count + 1).ToString()
                        : pageName;
                    ReadPage(archive, page, slide, textStyles);
                    document.Slides.Add(slide);
                }

                if (document.Slides.Count == 0)
                    document.AddSlide("Slide 1");
                return document;
            }
        }

        private static void ReadPage(
            ZipArchive archive,
            XmlNode page,
            PresentationSlide slide,
            Dictionary<string, TextStyle> textStyles)
        {
            for (int i = 0; i < page.ChildNodes.Count; i++)
            {
                XmlNode node = page.ChildNodes[i];
                if (node == null)
                    continue;

                if (node.LocalName == "frame")
                {
                    XmlNode textBox = FindChild(node, "text-box");
                    XmlNode image = FindChild(node, "image");
                    if (textBox != null)
                        ReadTextFrame(node, textBox, slide, textStyles);
                    else if (image != null)
                        ReadImageFrame(archive, node, image, slide);
                }
                else if (node.LocalName == "rect" || node.LocalName == "ellipse")
                {
                    PresentationShape shape = slide.AddShape(
                        node.LocalName == "ellipse"
                            ? PresentationShapeKind.Ellipse
                            : PresentationShapeKind.Rectangle);
                    shape.Name = OdfPackageUtility.GetAttributeByLocalName(node, "name");
                    ApplyGeometry(node, delegate(long x, long y, long w, long h)
                    {
                        shape.X = x;
                        shape.Y = y;
                        shape.Width = w;
                        shape.Height = h;
                    });
                }
            }
        }

        private static void ReadTextFrame(
            XmlNode frame,
            XmlNode textBoxNode,
            PresentationSlide slide,
            Dictionary<string, TextStyle> textStyles)
        {
            StringBuilder text = new StringBuilder();
            string styleName = string.Empty;

            for (int i = 0; i < textBoxNode.ChildNodes.Count; i++)
            {
                XmlNode paragraph = textBoxNode.ChildNodes[i];
                if (paragraph == null || (paragraph.LocalName != "p" && paragraph.LocalName != "h"))
                    continue;
                if (text.Length > 0)
                    text.Append('\n');
                text.Append(paragraph.InnerText ?? string.Empty);
                if (string.IsNullOrEmpty(styleName))
                    styleName = OdfPackageUtility.GetAttributeByLocalName(paragraph, "style-name");
            }

            PresentationTextBox box = slide.AddTextBox(text.ToString());
            box.Name = OdfPackageUtility.GetAttributeByLocalName(frame, "name");
            ApplyGeometry(frame, delegate(long x, long y, long w, long h)
            {
                box.X = x;
                box.Y = y;
                box.Width = w;
                box.Height = h;
            });

            TextStyle style;
            if (textStyles.TryGetValue(styleName, out style))
            {
                box.FontFamily = style.FontFamily;
                box.FontSizePoints = style.FontSize;
                box.Bold = style.Bold;
                box.Italic = style.Italic;
                box.ColorHex = style.Color;
                box.Alignment = style.Alignment;
            }
        }

        private static void ReadImageFrame(
            ZipArchive archive,
            XmlNode frame,
            XmlNode imageNode,
            PresentationSlide slide)
        {
            string href = OdfPackageUtility.GetAttributeByLocalName(imageNode, "href");
            if (string.IsNullOrEmpty(href))
                return;

            href = href.Replace('\\', '/').TrimStart('/');
            ZipArchiveEntry entry = archive.GetEntry(href);
            if (entry == null || entry.Length > 100L * 1024L * 1024L)
                return;

            byte[] data;
            using (Stream input = entry.Open())
            using (MemoryStream output = new MemoryStream())
            {
                input.CopyTo(output);
                data = output.ToArray();
            }

            PresentationImage image = slide.AddImage(
                data,
                Path.GetExtension(href).TrimStart('.'),
                GuessImageContentType(href));
            image.Name = OdfPackageUtility.GetAttributeByLocalName(frame, "name");
            ApplyGeometry(frame, delegate(long x, long y, long w, long h)
            {
                image.X = x;
                image.Y = y;
                image.Width = w;
                image.Height = h;
            });
        }

        private delegate void GeometryHandler(long x, long y, long width, long height);

        private static void ApplyGeometry(XmlNode node, GeometryHandler handler)
        {
            if (handler == null)
                return;
            handler(
                ParseLengthToEmu(OdfPackageUtility.GetAttributeByLocalName(node, "x"), 0),
                ParseLengthToEmu(OdfPackageUtility.GetAttributeByLocalName(node, "y"), 0),
                ParseLengthToEmu(OdfPackageUtility.GetAttributeByLocalName(node, "width"), 9144000),
                ParseLengthToEmu(OdfPackageUtility.GetAttributeByLocalName(node, "height"), 914400));
        }

        private static Dictionary<string, TextStyle> ReadTextStyles(XmlDocument document)
        {
            Dictionary<string, TextStyle> result =
                new Dictionary<string, TextStyle>(StringComparer.Ordinal);
            XmlNodeList nodes = document.GetElementsByTagName("*");

            for (int i = 0; i < nodes.Count; i++)
            {
                XmlNode styleNode = nodes[i];
                if (styleNode == null || styleNode.LocalName != "style")
                    continue;
                string name = OdfPackageUtility.GetAttributeByLocalName(styleNode, "name");
                string family = OdfPackageUtility.GetAttributeByLocalName(styleNode, "family");
                if (string.IsNullOrEmpty(name) || family != "paragraph")
                    continue;

                TextStyle style = new TextStyle();
                XmlNode textProps = FindChild(styleNode, "text-properties");
                XmlNode paraProps = FindChild(styleNode, "paragraph-properties");
                if (textProps != null)
                {
                    string font = OdfPackageUtility.GetAttributeByLocalName(textProps, "font-family");
                    if (!string.IsNullOrEmpty(font))
                        style.FontFamily = font.Trim('\'', '"');
                    style.FontSize = ParsePointSize(
                        OdfPackageUtility.GetAttributeByLocalName(textProps, "font-size"), 20f);
                    style.Bold = string.Equals(
                        OdfPackageUtility.GetAttributeByLocalName(textProps, "font-weight"),
                        "bold",
                        StringComparison.OrdinalIgnoreCase);
                    style.Italic = string.Equals(
                        OdfPackageUtility.GetAttributeByLocalName(textProps, "font-style"),
                        "italic",
                        StringComparison.OrdinalIgnoreCase);
                    style.Color = NormalizeColor(
                        OdfPackageUtility.GetAttributeByLocalName(textProps, "color"));
                }
                if (paraProps != null)
                {
                    string align = OdfPackageUtility.GetAttributeByLocalName(paraProps, "text-align");
                    if (align == "center")
                        style.Alignment = PresentationTextAlignment.Center;
                    else if (align == "right" || align == "end")
                        style.Alignment = PresentationTextAlignment.Right;
                }
                result[name] = style;
            }

            return result;
        }

        private static string ReadTitle(ZipArchive archive)
        {
            XmlDocument meta = OdfPackageUtility.LoadXml(archive, "meta.xml");
            XmlNode title = FindFirst(meta, "title");
            return title == null || string.IsNullOrEmpty(title.InnerText)
                ? "ODP Presentation"
                : title.InnerText;
        }

        private static XmlNode FindFirst(XmlDocument document, string localName)
        {
            if (document == null)
                return null;
            XmlNodeList nodes = document.GetElementsByTagName("*");
            for (int i = 0; i < nodes.Count; i++)
                if (nodes[i] != null && nodes[i].LocalName == localName)
                    return nodes[i];
            return null;
        }

        private static XmlNode FindChild(XmlNode parent, string localName)
        {
            if (parent == null)
                return null;
            for (int i = 0; i < parent.ChildNodes.Count; i++)
                if (parent.ChildNodes[i] != null && parent.ChildNodes[i].LocalName == localName)
                    return parent.ChildNodes[i];
            return null;
        }

        private static long ParseLengthToEmu(string value, long fallback)
        {
            string text = (value ?? string.Empty).Trim().ToLowerInvariant();
            if (text.Length == 0)
                return fallback;

            double factor;
            string numeric;
            if (text.EndsWith("cm"))
            {
                factor = 360000.0;
                numeric = text.Substring(0, text.Length - 2);
            }
            else if (text.EndsWith("mm"))
            {
                factor = 36000.0;
                numeric = text.Substring(0, text.Length - 2);
            }
            else if (text.EndsWith("in"))
            {
                factor = 914400.0;
                numeric = text.Substring(0, text.Length - 2);
            }
            else if (text.EndsWith("pt"))
            {
                factor = 12700.0;
                numeric = text.Substring(0, text.Length - 2);
            }
            else
            {
                factor = 360000.0;
                numeric = text;
            }

            double parsed;
            if (!double.TryParse(numeric, NumberStyles.Float, CultureInfo.InvariantCulture, out parsed))
                return fallback;
            return Math.Max(0L, (long)Math.Round(parsed * factor));
        }

        private static float ParsePointSize(string value, float fallback)
        {
            string text = (value ?? string.Empty).Trim();
            if (text.EndsWith("pt", StringComparison.OrdinalIgnoreCase))
                text = text.Substring(0, text.Length - 2);
            float parsed;
            return float.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out parsed)
                ? Math.Max(1f, Math.Min(400f, parsed))
                : fallback;
        }

        private static string NormalizeColor(string value)
        {
            string text = (value ?? string.Empty).Trim().TrimStart('#').ToUpperInvariant();
            int parsed;
            if (text.Length == 6 && int.TryParse(text, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out parsed))
                return text;
            return "20242A";
        }

        private static string GuessImageContentType(string path)
        {
            string extension = Path.GetExtension(path).ToLowerInvariant();
            if (extension == ".jpg" || extension == ".jpeg") return "image/jpeg";
            if (extension == ".gif") return "image/gif";
            if (extension == ".bmp") return "image/bmp";
            return "image/png";
        }
    }

    internal static class OdpWriter
    {
        public static void Save(PresentationDocument document, string path)
        {
            if (document == null)
                throw new ArgumentNullException("document");
            if (string.IsNullOrEmpty(path))
                throw new ArgumentException("Destination path is required.", "path");

            string destination = Path.GetFullPath(path);
            if (!string.Equals(Path.GetExtension(destination), ".odp", StringComparison.OrdinalIgnoreCase))
                destination = Path.ChangeExtension(destination, "odp");

            string directory = Path.GetDirectoryName(destination);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);

            string stage = destination + ".writing";
            string backup = destination + ".backup";
            OdfPackageUtility.DeleteIfExists(stage);
            OdfPackageUtility.DeleteIfExists(backup);

            try
            {
                using (FileStream file = new FileStream(stage, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.None))
                using (ZipArchive archive = new ZipArchive(file, ZipArchiveMode.Create, false))
                {
                    OdfPackageUtility.WriteTextEntry(
                        archive, "mimetype", OdfPackageUtility.PresentationMimeType, CompressionLevel.NoCompression);

                    List<OdfManifestEntry> manifest = new List<OdfManifestEntry>();
                    manifest.Add(new OdfManifestEntry("content.xml", "text/xml"));
                    manifest.Add(new OdfManifestEntry("styles.xml", "text/xml"));
                    manifest.Add(new OdfManifestEntry("meta.xml", "text/xml"));

                    string content = BuildContentXml(document, archive, manifest);
                    OdfPackageUtility.WriteTextEntry(archive, "content.xml", content, CompressionLevel.Optimal);
                    OdfPackageUtility.WriteTextEntry(archive, "styles.xml", BuildStylesXml(), CompressionLevel.Optimal);
                    OdfPackageUtility.WriteTextEntry(
                        archive, "meta.xml", OdfPackageUtility.BuildMetaXml(document.Title), CompressionLevel.Optimal);
                    OdfPackageUtility.WriteTextEntry(
                        archive,
                        "META-INF/manifest.xml",
                        OdfPackageUtility.BuildManifest(OdfDocumentKind.Presentation, manifest),
                        CompressionLevel.Optimal);
                }

                OdfPackageUtility.ReplaceSafely(stage, destination, backup);
            }
            catch
            {
                OdfPackageUtility.DeleteIfExists(stage);
                throw;
            }
        }

        private static string BuildContentXml(
            PresentationDocument document,
            ZipArchive archive,
            List<OdfManifestEntry> manifest)
        {
            StringBuilder xml = new StringBuilder();
            xml.Append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
            xml.Append("<office:document-content ");
            xml.Append("xmlns:office=\"urn:oasis:names:tc:opendocument:xmlns:office:1.0\" ");
            xml.Append("xmlns:draw=\"urn:oasis:names:tc:opendocument:xmlns:drawing:1.0\" ");
            xml.Append("xmlns:text=\"urn:oasis:names:tc:opendocument:xmlns:text:1.0\" ");
            xml.Append("xmlns:style=\"urn:oasis:names:tc:opendocument:xmlns:style:1.0\" ");
            xml.Append("xmlns:fo=\"urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0\" ");
            xml.Append("xmlns:svg=\"urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0\" ");
            xml.Append("xmlns:xlink=\"http://www.w3.org/1999/xlink\" ");
            xml.Append("xmlns:presentation=\"urn:oasis:names:tc:opendocument:xmlns:presentation:1.0\" ");
            xml.Append("office:version=\"1.3\">");
            xml.Append("<office:automatic-styles>");
            xml.Append("<style:style style:name=\"gr1\" style:family=\"graphic\"><style:graphic-properties draw:fill=\"none\" draw:stroke=\"none\"/></style:style>");
            xml.Append("<style:style style:name=\"grShape\" style:family=\"graphic\"><style:graphic-properties draw:fill=\"solid\" draw:fill-color=\"#5B8CFF\" draw:stroke=\"solid\" svg:stroke-color=\"#356AE6\"/></style:style>");

            int textStyleId = 0;
            for (int s = 0; s < document.Slides.Count; s++)
            {
                PresentationSlide slide = document.Slides[s];
                if (slide == null)
                    continue;
                for (int t = 0; t < slide.TextBoxes.Count; t++)
                {
                    xml.Append(BuildTextStyle(slide.TextBoxes[t], textStyleId));
                    textStyleId++;
                }
            }

            xml.Append("</office:automatic-styles><office:body><office:presentation>");

            int nextTextStyle = 0;
            int imageId = 1;
            for (int s = 0; s < document.Slides.Count; s++)
            {
                PresentationSlide slide = document.Slides[s];
                if (slide == null)
                    continue;

                xml.Append("<draw:page draw:name=\"");
                xml.Append(OdfPackageUtility.EscapeXml(
                    string.IsNullOrEmpty(slide.Name) ? "Slide " + (s + 1).ToString() : slide.Name));
                xml.Append("\" draw:style-name=\"dp1\" draw:master-page-name=\"Default\">");

                for (int t = 0; t < slide.TextBoxes.Count; t++)
                {
                    PresentationTextBox box = slide.TextBoxes[t];
                    if (box == null)
                        continue;
                    xml.Append("<draw:frame draw:style-name=\"gr1\" draw:name=\"");
                    xml.Append(OdfPackageUtility.EscapeXml(box.Name));
                    xml.Append("\"");
                    AppendGeometry(xml, box.X, box.Y, box.Width, box.Height);
                    xml.Append("><draw:text-box><text:p text:style-name=\"P");
                    xml.Append(nextTextStyle.ToString(CultureInfo.InvariantCulture));
                    xml.Append("\">");
                    xml.Append(OdfPackageUtility.EscapeXml(box.Text ?? string.Empty));
                    xml.Append("</text:p></draw:text-box></draw:frame>");
                    nextTextStyle++;
                }

                for (int sh = 0; sh < slide.Shapes.Count; sh++)
                {
                    PresentationShape shape = slide.Shapes[sh];
                    if (shape == null)
                        continue;
                    string element = shape.Kind == PresentationShapeKind.Ellipse ? "ellipse" : "rect";
                    xml.Append("<draw:");
                    xml.Append(element);
                    xml.Append(" draw:style-name=\"grShape\" draw:name=\"");
                    xml.Append(OdfPackageUtility.EscapeXml(shape.Name));
                    xml.Append("\"");
                    AppendGeometry(xml, shape.X, shape.Y, shape.Width, shape.Height);
                    xml.Append("/>");
                }

                for (int im = 0; im < slide.Images.Count; im++)
                {
                    PresentationImage image = slide.Images[im];
                    if (image == null || image.Data == null || image.Data.Length == 0)
                        continue;

                    string extension = string.IsNullOrEmpty(image.Extension) ? "png" : image.Extension.TrimStart('.');
                    string picturePath = "Pictures/image" + imageId.ToString(CultureInfo.InvariantCulture) + "." + extension;
                    ZipArchiveEntry entry = archive.CreateEntry(picturePath, CompressionLevel.Optimal);
                    using (Stream output = entry.Open())
                        output.Write(image.Data, 0, image.Data.Length);
                    manifest.Add(new OdfManifestEntry(
                        picturePath,
                        string.IsNullOrEmpty(image.ContentType) ? "image/png" : image.ContentType));

                    xml.Append("<draw:frame draw:style-name=\"gr1\" draw:name=\"");
                    xml.Append(OdfPackageUtility.EscapeXml(image.Name));
                    xml.Append("\"");
                    AppendGeometry(xml, image.X, image.Y, image.Width, image.Height);
                    xml.Append("><draw:image xlink:href=\"");
                    xml.Append(OdfPackageUtility.EscapeXml(picturePath));
                    xml.Append("\" xlink:type=\"simple\" xlink:show=\"embed\" xlink:actuate=\"onLoad\"/></draw:frame>");
                    imageId++;
                }

                xml.Append("</draw:page>");
            }

            if (document.Slides.Count == 0)
                xml.Append("<draw:page draw:name=\"Slide 1\" draw:style-name=\"dp1\" draw:master-page-name=\"Default\"/>");

            xml.Append("</office:presentation></office:body></office:document-content>");
            return xml.ToString();
        }

        private static string BuildTextStyle(PresentationTextBox box, int id)
        {
            if (box == null)
                box = new PresentationTextBox();

            string align = box.Alignment == PresentationTextAlignment.Center
                ? "center"
                : box.Alignment == PresentationTextAlignment.Right ? "end" : "start";

            StringBuilder xml = new StringBuilder();
            xml.Append("<style:style style:name=\"P");
            xml.Append(id.ToString(CultureInfo.InvariantCulture));
            xml.Append("\" style:family=\"paragraph\"><style:paragraph-properties fo:text-align=\"");
            xml.Append(align);
            xml.Append("\"/><style:text-properties fo:font-family=\"");
            xml.Append(OdfPackageUtility.EscapeXml(
                string.IsNullOrEmpty(box.FontFamily) ? "Arial" : box.FontFamily));
            xml.Append("\" fo:font-size=\"");
            xml.Append(Math.Max(1f, box.FontSizePoints).ToString("0.##", CultureInfo.InvariantCulture));
            xml.Append("pt\" fo:color=\"#");
            xml.Append(NormalizeColor(box.ColorHex));
            xml.Append("\"");
            if (box.Bold)
                xml.Append(" fo:font-weight=\"bold\"");
            if (box.Italic)
                xml.Append(" fo:font-style=\"italic\"");
            xml.Append("/></style:style>");
            return xml.ToString();
        }

        private static void AppendGeometry(
            StringBuilder xml,
            long x,
            long y,
            long width,
            long height)
        {
            xml.Append(" svg:x=\"");
            xml.Append(EmuToCm(x));
            xml.Append("\" svg:y=\"");
            xml.Append(EmuToCm(y));
            xml.Append("\" svg:width=\"");
            xml.Append(EmuToCm(width));
            xml.Append("\" svg:height=\"");
            xml.Append(EmuToCm(height));
            xml.Append("\"");
        }

        private static string EmuToCm(long emu)
        {
            return Math.Max(0.0, emu / 360000.0)
                .ToString("0.####", CultureInfo.InvariantCulture) + "cm";
        }

        private static string BuildStylesXml()
        {
            return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<office:document-styles " +
                "xmlns:office=\"urn:oasis:names:tc:opendocument:xmlns:office:1.0\" " +
                "xmlns:style=\"urn:oasis:names:tc:opendocument:xmlns:style:1.0\" " +
                "xmlns:draw=\"urn:oasis:names:tc:opendocument:xmlns:drawing:1.0\" " +
                "xmlns:presentation=\"urn:oasis:names:tc:opendocument:xmlns:presentation:1.0\" " +
                "xmlns:svg=\"urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0\" " +
                "office:version=\"1.3\">" +
                "<office:styles/>" +
                "<office:automatic-styles><style:page-layout style:name=\"PM1\"><style:page-layout-properties fo:page-width=\"33.867cm\" fo:page-height=\"19.05cm\" print-orientation=\"landscape\"/></style:page-layout></office:automatic-styles>" +
                "<office:master-styles><style:master-page style:name=\"Default\" style:page-layout-name=\"PM1\" draw:style-name=\"dp1\"/></office:master-styles>" +
                "</office:document-styles>";
        }

        private static string NormalizeColor(string value)
        {
            string text = (value ?? string.Empty).Trim().TrimStart('#').ToUpperInvariant();
            int parsed;
            if (text.Length == 6 && int.TryParse(text, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out parsed))
                return text;
            return "20242A";
        }
    }
}
