using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Text;
using System.Xml;

namespace PptxViewer
{
    internal sealed class OdsEditSafetyResult
    {
        public bool IsOdsPackage { get; set; }
        public bool IsProjectGenerated { get; set; }
        public bool HasUnsupportedContent { get; set; }
        public bool CanEditSafely { get; set; }
        public string Warning { get; set; }

        public OdsEditSafetyResult()
        {
            Warning = string.Empty;
        }
    }

    internal static class OdsEditSafety
    {
        public static OdsEditSafetyResult Analyze(string path)
        {
            if (string.IsNullOrEmpty(path) || !File.Exists(path))
                throw new FileNotFoundException("ODS file was not found.", path);

            OdsEditSafetyResult result = new OdsEditSafetyResult();

            using (ZipArchive archive = ZipFile.OpenRead(path))
            {
                result.IsOdsPackage = string.Equals(
                    OdfPackageUtility.ReadTextEntry(archive, "mimetype").Trim(),
                    OdfPackageUtility.SpreadsheetMimeType,
                    StringComparison.Ordinal);
                result.IsProjectGenerated = OdfPackageUtility.IsProjectGenerated(archive);

                List<string> allowed = new List<string>();
                allowed.Add("mimetype");
                allowed.Add("content.xml");
                allowed.Add("styles.xml");
                allowed.Add("meta.xml");
                allowed.Add("META-INF/manifest.xml");
                result.HasUnsupportedContent =
                    !OdfPackageUtility.ContainsOnlyKnownParts(archive, allowed);
            }

            result.CanEditSafely =
                result.IsOdsPackage &&
                result.IsProjectGenerated &&
                !result.HasUnsupportedContent;

            if (!result.CanEditSafely)
            {
                if (!result.IsOdsPackage)
                    result.Warning = "The file is not recognized as an ODS package.";
                else if (!result.IsProjectGenerated)
                    result.Warning = "This ODS was not generated by the current experimental writer. Editing is disabled until preservation support is broader.";
                else
                    result.Warning = "This ODS contains package content that the experimental writer does not preserve.";
            }

            return result;
        }
    }

    internal static class OdsReader
    {
        public static SpreadsheetDocument Read(string path)
        {
            if (!OdfPackageUtility.HasExpectedMimeType(path, OdfDocumentKind.Spreadsheet))
                throw new InvalidDataException("The package mimetype is not ODS.");

            using (ZipArchive archive = ZipFile.OpenRead(path))
            {
                XmlDocument content = OdfPackageUtility.LoadXml(archive, "content.xml");
                if (content == null || content.DocumentElement == null)
                    throw new InvalidDataException("ODS content.xml is missing.");

                SpreadsheetDocument document =
                    new SpreadsheetDocument(ReadTitle(archive));

                XmlNode spreadsheet = FindFirst(content, "spreadsheet");
                if (spreadsheet == null)
                    throw new InvalidDataException("ODS office:spreadsheet body is missing.");

                for (int i = 0; i < spreadsheet.ChildNodes.Count; i++)
                {
                    XmlNode tableNode = spreadsheet.ChildNodes[i];
                    if (tableNode == null || tableNode.LocalName != "table")
                        continue;

                    string name = OdfPackageUtility.GetAttributeByLocalName(tableNode, "name");
                    SpreadsheetSheet sheet = document.AddSheet(
                        string.IsNullOrEmpty(name) ? "Sheet" : name);
                    ReadSheet(tableNode, sheet);
                }

                if (document.Sheets.Count == 0)
                    document.AddSheet("Sheet1");

                return document;
            }
        }

        private static void ReadSheet(XmlNode tableNode, SpreadsheetSheet sheet)
        {
            int rowNumber = 1;

            for (int i = 0; i < tableNode.ChildNodes.Count; i++)
            {
                XmlNode rowNode = tableNode.ChildNodes[i];
                if (rowNode == null || rowNode.LocalName != "table-row")
                    continue;

                int repeatedRows = ParsePositiveInt(
                    OdfPackageUtility.GetAttributeByLocalName(rowNode, "number-rows-repeated"),
                    1,
                    10000);

                for (int repeatRow = 0; repeatRow < repeatedRows; repeatRow++)
                {
                    int columnNumber = 1;

                    for (int c = 0; c < rowNode.ChildNodes.Count; c++)
                    {
                        XmlNode cellNode = rowNode.ChildNodes[c];
                        if (cellNode == null ||
                            (cellNode.LocalName != "table-cell" &&
                             cellNode.LocalName != "covered-table-cell"))
                        {
                            continue;
                        }

                        int repeatedColumns = ParsePositiveInt(
                            OdfPackageUtility.GetAttributeByLocalName(cellNode, "number-columns-repeated"),
                            1,
                            10000);

                        for (int repeatColumn = 0; repeatColumn < repeatedColumns; repeatColumn++)
                        {
                            if (cellNode.LocalName == "table-cell")
                                ReadCell(cellNode, sheet, rowNumber, columnNumber);
                            columnNumber++;
                        }
                    }

                    rowNumber++;
                    if (rowNumber > 1000000)
                        throw new InvalidDataException("ODS row count exceeds the safety limit.");
                }
            }
        }

        private static void ReadCell(
            XmlNode node,
            SpreadsheetSheet sheet,
            int row,
            int column)
        {
            string formula = OdfPackageUtility.GetAttributeByLocalName(node, "formula");
            if (!string.IsNullOrEmpty(formula))
            {
                if (formula.StartsWith("of:", StringComparison.OrdinalIgnoreCase))
                    formula = formula.Substring(3);
                sheet.SetInput(row, column, formula);
                return;
            }

            string type = OdfPackageUtility.GetAttributeByLocalName(node, "value-type");

            if (string.Equals(type, "float", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(type, "currency", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(type, "percentage", StringComparison.OrdinalIgnoreCase))
            {
                string value = OdfPackageUtility.GetAttributeByLocalName(node, "value");
                double number;
                if (double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out number))
                {
                    sheet.SetNumber(row, column, number);
                    return;
                }
            }

            if (string.Equals(type, "boolean", StringComparison.OrdinalIgnoreCase))
            {
                string value = OdfPackageUtility.GetAttributeByLocalName(node, "boolean-value");
                sheet.SetBoolean(row, column,
                    string.Equals(value, "true", StringComparison.OrdinalIgnoreCase) || value == "1");
                return;
            }

            string text = CollectText(node);
            if (!string.IsNullOrEmpty(text))
                sheet.SetText(row, column, text);
        }

        private static string CollectText(XmlNode node)
        {
            StringBuilder result = new StringBuilder();
            AppendText(node, result);
            return result.ToString();
        }

        private static void AppendText(XmlNode node, StringBuilder result)
        {
            if (node == null)
                return;

            for (int i = 0; i < node.ChildNodes.Count; i++)
            {
                XmlNode child = node.ChildNodes[i];
                if (child == null)
                    continue;

                if (child.NodeType == XmlNodeType.Text || child.NodeType == XmlNodeType.CDATA)
                    result.Append(child.Value ?? string.Empty);
                else if (child.LocalName == "line-break")
                    result.Append('\n');
                else if (child.LocalName == "tab")
                    result.Append('\t');
                else if (child.LocalName == "s")
                {
                    int count = ParsePositiveInt(
                        OdfPackageUtility.GetAttributeByLocalName(child, "c"), 1, 10000);
                    result.Append(new string(' ', count));
                }
                else
                    AppendText(child, result);
            }
        }

        private static string ReadTitle(ZipArchive archive)
        {
            XmlDocument meta = OdfPackageUtility.LoadXml(archive, "meta.xml");
            XmlNode title = FindFirst(meta, "title");
            return title == null || string.IsNullOrEmpty(title.InnerText)
                ? "ODS Workbook"
                : title.InnerText;
        }

        private static XmlNode FindFirst(XmlDocument document, string localName)
        {
            if (document == null)
                return null;
            XmlNodeList nodes = document.GetElementsByTagName("*");
            for (int i = 0; i < nodes.Count; i++)
                if (nodes[i] != null && nodes[i].LocalName == localName)
                    return nodes[i];
            return null;
        }

        private static int ParsePositiveInt(string value, int fallback, int max)
        {
            int parsed;
            if (!int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out parsed) || parsed < 1)
                return fallback;
            return Math.Min(parsed, max);
        }
    }

    internal static class OdsWriter
    {
        public static void Save(SpreadsheetDocument document, string path)
        {
            if (document == null)
                throw new ArgumentNullException("document");
            if (string.IsNullOrEmpty(path))
                throw new ArgumentException("Destination path is required.", "path");

            string destination = Path.GetFullPath(path);
            if (!string.Equals(Path.GetExtension(destination), ".ods", StringComparison.OrdinalIgnoreCase))
                destination = Path.ChangeExtension(destination, "ods");

            string directory = Path.GetDirectoryName(destination);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);

            string stage = destination + ".writing";
            string backup = destination + ".backup";
            OdfPackageUtility.DeleteIfExists(stage);
            OdfPackageUtility.DeleteIfExists(backup);

            try
            {
                using (FileStream file = new FileStream(stage, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.None))
                using (ZipArchive archive = new ZipArchive(file, ZipArchiveMode.Create, false))
                {
                    OdfPackageUtility.WriteTextEntry(
                        archive, "mimetype", OdfPackageUtility.SpreadsheetMimeType, CompressionLevel.NoCompression);
                    OdfPackageUtility.WriteTextEntry(
                        archive, "content.xml", BuildContentXml(document), CompressionLevel.Optimal);
                    OdfPackageUtility.WriteTextEntry(
                        archive, "styles.xml", BuildStylesXml(), CompressionLevel.Optimal);
                    OdfPackageUtility.WriteTextEntry(
                        archive, "meta.xml", OdfPackageUtility.BuildMetaXml(document.Title), CompressionLevel.Optimal);

                    List<OdfManifestEntry> manifest = new List<OdfManifestEntry>();
                    manifest.Add(new OdfManifestEntry("content.xml", "text/xml"));
                    manifest.Add(new OdfManifestEntry("styles.xml", "text/xml"));
                    manifest.Add(new OdfManifestEntry("meta.xml", "text/xml"));
                    OdfPackageUtility.WriteTextEntry(
                        archive,
                        "META-INF/manifest.xml",
                        OdfPackageUtility.BuildManifest(OdfDocumentKind.Spreadsheet, manifest),
                        CompressionLevel.Optimal);
                }

                OdfPackageUtility.ReplaceSafely(stage, destination, backup);
            }
            catch
            {
                OdfPackageUtility.DeleteIfExists(stage);
                throw;
            }
        }

        private static string BuildContentXml(SpreadsheetDocument document)
        {
            StringBuilder xml = new StringBuilder();
            xml.Append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
            xml.Append("<office:document-content ");
            xml.Append("xmlns:office=\"urn:oasis:names:tc:opendocument:xmlns:office:1.0\" ");
            xml.Append("xmlns:table=\"urn:oasis:names:tc:opendocument:xmlns:table:1.0\" ");
            xml.Append("xmlns:text=\"urn:oasis:names:tc:opendocument:xmlns:text:1.0\" ");
            xml.Append("office:version=\"1.3\"><office:body><office:spreadsheet>");

            for (int s = 0; s < document.Sheets.Count; s++)
            {
                SpreadsheetSheet sheet = document.Sheets[s];
                if (sheet == null)
                    continue;

                xml.Append("<table:table table:name=\"");
                xml.Append(OdfPackageUtility.EscapeXml(sheet.Name));
                xml.Append("\">");
                AppendSheet(xml, sheet);
                xml.Append("</table:table>");
            }

            if (document.Sheets.Count == 0)
                xml.Append("<table:table table:name=\"Sheet1\"><table:table-row/></table:table>");

            xml.Append("</office:spreadsheet></office:body></office:document-content>");
            return xml.ToString();
        }

        private static void AppendSheet(StringBuilder xml, SpreadsheetSheet sheet)
        {
            List<SpreadsheetCell> cells = sheet.GetCellsSorted();
            int index = 0;
            int maxRow = Math.Max(1, sheet.MaxRow);

            for (int row = 1; row <= maxRow; row++)
            {
                xml.Append("<table:table-row>");
                int currentColumn = 1;

                while (index < cells.Count && cells[index].Row == row)
                {
                    SpreadsheetCell cell = cells[index];
                    if (cell.Column > currentColumn)
                    {
                        AppendEmptyCells(xml, cell.Column - currentColumn);
                        currentColumn = cell.Column;
                    }

                    AppendCell(xml, cell);
                    currentColumn++;
                    index++;
                }

                xml.Append("</table:table-row>");
            }
        }

        private static void AppendEmptyCells(StringBuilder xml, int count)
        {
            if (count <= 0)
                return;
            if (count == 1)
            {
                xml.Append("<table:table-cell/>");
                return;
            }
            xml.Append("<table:table-cell table:number-columns-repeated=\"");
            xml.Append(count.ToString(CultureInfo.InvariantCulture));
            xml.Append("\"/>");
        }

        private static void AppendCell(StringBuilder xml, SpreadsheetCell cell)
        {
            if (cell == null || cell.Kind == SpreadsheetCellKind.Blank)
            {
                xml.Append("<table:table-cell/>");
                return;
            }

            if (cell.Kind == SpreadsheetCellKind.Number)
            {
                string number = cell.NumberValue.ToString("R", CultureInfo.InvariantCulture);
                xml.Append("<table:table-cell office:value-type=\"float\" office:value=\"");
                xml.Append(number);
                xml.Append("\"><text:p>");
                xml.Append(number);
                xml.Append("</text:p></table:table-cell>");
                return;
            }

            if (cell.Kind == SpreadsheetCellKind.Boolean)
            {
                string boolean = cell.BooleanValue ? "true" : "false";
                xml.Append("<table:table-cell office:value-type=\"boolean\" office:boolean-value=\"");
                xml.Append(boolean);
                xml.Append("\"><text:p>");
                xml.Append(boolean.ToUpperInvariant());
                xml.Append("</text:p></table:table-cell>");
                return;
            }

            if (cell.Kind == SpreadsheetCellKind.Formula)
            {
                string formula = cell.Formula ?? string.Empty;
                xml.Append("<table:table-cell table:formula=\"of:");
                xml.Append(OdfPackageUtility.EscapeXml(formula));
                xml.Append("\" office:value-type=\"string\"><text:p>");
                xml.Append(OdfPackageUtility.EscapeXml(formula));
                xml.Append("</text:p></table:table-cell>");
                return;
            }

            xml.Append("<table:table-cell office:value-type=\"string\"><text:p>");
            xml.Append(OdfPackageUtility.EscapeXml(cell.TextValue ?? string.Empty));
            xml.Append("</text:p></table:table-cell>");
        }

        private static string BuildStylesXml()
        {
            return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<office:document-styles " +
                "xmlns:office=\"urn:oasis:names:tc:opendocument:xmlns:office:1.0\" " +
                "xmlns:style=\"urn:oasis:names:tc:opendocument:xmlns:style:1.0\" " +
                "office:version=\"1.3\"><office:styles/></office:document-styles>";
        }
    }
}
