using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Text;
using System.Xml;

namespace PptxViewer
{
    internal sealed class OdtEditSafetyResult
    {
        public bool IsOdtPackage { get; set; }
        public bool IsProjectGenerated { get; set; }
        public bool HasUnsupportedContent { get; set; }
        public bool CanEditSafely { get; set; }
        public string Warning { get; set; }

        public OdtEditSafetyResult()
        {
            Warning = string.Empty;
        }
    }

    internal static class OdtEditSafety
    {
        public static OdtEditSafetyResult Analyze(string path)
        {
            if (string.IsNullOrEmpty(path) || !File.Exists(path))
                throw new FileNotFoundException("ODT file was not found.", path);

            OdtEditSafetyResult result = new OdtEditSafetyResult();

            using (ZipArchive archive = ZipFile.OpenRead(path))
            {
                result.IsOdtPackage = string.Equals(
                    OdfPackageUtility.ReadTextEntry(archive, "mimetype").Trim(),
                    OdfPackageUtility.TextMimeType,
                    StringComparison.Ordinal);
                result.IsProjectGenerated = OdfPackageUtility.IsProjectGenerated(archive);

                List<string> allowed = new List<string>();
                allowed.Add("mimetype");
                allowed.Add("content.xml");
                allowed.Add("styles.xml");
                allowed.Add("meta.xml");
                allowed.Add("META-INF/manifest.xml");
                result.HasUnsupportedContent =
                    !OdfPackageUtility.ContainsOnlyKnownParts(archive, allowed) ||
                    ContainsEncryptionMetadata(archive);
            }

            result.CanEditSafely =
                result.IsOdtPackage &&
                result.IsProjectGenerated &&
                !result.HasUnsupportedContent;

            if (!result.CanEditSafely)
            {
                if (!result.IsOdtPackage)
                    result.Warning = "The file is not recognized as an ODT package.";
                else if (!result.IsProjectGenerated)
                    result.Warning = "This ODT was not generated by the current experimental writer. Editing is disabled until preservation support is broader.";
                else
                    result.Warning = "This ODT contains unsupported or encrypted package content and will not be rewritten.";
            }

            return result;
        }

        private static bool ContainsEncryptionMetadata(ZipArchive archive)
        {
            XmlDocument manifest =
                OdfPackageUtility.LoadXml(archive, "META-INF/manifest.xml");
            if (manifest == null || manifest.DocumentElement == null)
                return false;

            XmlNodeList nodes = manifest.GetElementsByTagName("*");
            for (int i = 0; i < nodes.Count; i++)
            {
                string local = nodes[i] == null ? string.Empty : nodes[i].LocalName;
                if (local == "encryption-data" || local == "algorithm" || local == "key-derivation")
                    return true;
            }
            return false;
        }
    }

    internal static class OdtReader
    {
        private sealed class RunStyle
        {
            public string FontFamily = "Arial";
            public float FontSize = 11f;
            public bool Bold;
            public bool Italic;
            public bool Underline;
            public string Color = "20242A";
        }

        public static TextDocument Read(string path)
        {
            if (!OdfPackageUtility.HasExpectedMimeType(path, OdfDocumentKind.Text))
                throw new InvalidDataException("The package mimetype is not ODT.");

            using (ZipArchive archive = ZipFile.OpenRead(path))
            {
                XmlDocument content = OdfPackageUtility.LoadXml(archive, "content.xml");
                if (content == null || content.DocumentElement == null)
                    throw new InvalidDataException("ODT content.xml is missing.");

                Dictionary<string, RunStyle> runStyles = new Dictionary<string, RunStyle>(StringComparer.Ordinal);
                Dictionary<string, DocumentParagraphAlignment> paraStyles =
                    new Dictionary<string, DocumentParagraphAlignment>(StringComparer.Ordinal);

                ReadStyles(content, runStyles, paraStyles);

                XmlDocument styles = OdfPackageUtility.LoadXml(archive, "styles.xml");
                if (styles != null)
                    ReadStyles(styles, runStyles, paraStyles);

                TextDocument document = TextDocument.CreateNew(ReadTitle(archive));
                XmlNode officeText = FindFirst(content, "text");
                if (officeText == null)
                    throw new InvalidDataException("ODT office:text body is missing.");

                for (int i = 0; i < officeText.ChildNodes.Count; i++)
                {
                    XmlNode node = officeText.ChildNodes[i];
                    if (node == null || (node.LocalName != "p" && node.LocalName != "h"))
                        continue;

                    DocumentParagraph paragraph = new DocumentParagraph();
                    string paragraphStyle = OdfPackageUtility.GetAttributeByLocalName(node, "style-name");
                    DocumentParagraphAlignment alignment;
                    if (paraStyles.TryGetValue(paragraphStyle, out alignment))
                        paragraph.Alignment = alignment;

                    AppendParagraphContent(node, paragraph, runStyles, null);
                    if (paragraph.Runs.Count == 0)
                        paragraph.AddRun(string.Empty);
                    document.Paragraphs.Add(paragraph);
                }

                if (document.Paragraphs.Count == 0)
                    document.AddParagraph(string.Empty);
                return document;
            }
        }

        private static void AppendParagraphContent(
            XmlNode parent,
            DocumentParagraph paragraph,
            Dictionary<string, RunStyle> styles,
            RunStyle inherited)
        {
            for (int i = 0; i < parent.ChildNodes.Count; i++)
            {
                XmlNode child = parent.ChildNodes[i];
                if (child == null)
                    continue;

                if (child.NodeType == XmlNodeType.Text || child.NodeType == XmlNodeType.CDATA)
                {
                    AppendRun(paragraph, child.Value ?? string.Empty, inherited);
                }
                else if (child.LocalName == "span")
                {
                    string styleName = OdfPackageUtility.GetAttributeByLocalName(child, "style-name");
                    RunStyle style;
                    if (!styles.TryGetValue(styleName, out style))
                        style = inherited;
                    AppendParagraphContent(child, paragraph, styles, style);
                }
                else if (child.LocalName == "tab")
                {
                    AppendRun(paragraph, "\t", inherited);
                }
                else if (child.LocalName == "line-break")
                {
                    AppendRun(paragraph, "\n", inherited);
                }
                else if (child.LocalName == "s")
                {
                    int count = ParseInt(OdfPackageUtility.GetAttributeByLocalName(child, "c"), 1);
                    if (count < 1) count = 1;
                    if (count > 10000) count = 10000;
                    AppendRun(paragraph, new string(' ', count), inherited);
                }
                else
                {
                    AppendParagraphContent(child, paragraph, styles, inherited);
                }
            }
        }

        private static void AppendRun(
            DocumentParagraph paragraph,
            string text,
            RunStyle style)
        {
            if (string.IsNullOrEmpty(text))
                return;

            DocumentTextRun run = paragraph.AddRun(text);
            if (style == null)
                return;

            run.FontFamily = style.FontFamily;
            run.FontSizePoints = style.FontSize;
            run.Bold = style.Bold;
            run.Italic = style.Italic;
            run.Underline = style.Underline;
            run.ColorHex = style.Color;
        }

        private static void ReadStyles(
            XmlDocument document,
            Dictionary<string, RunStyle> runStyles,
            Dictionary<string, DocumentParagraphAlignment> paraStyles)
        {
            if (document == null || document.DocumentElement == null)
                return;

            XmlNodeList nodes = document.GetElementsByTagName("*");
            for (int i = 0; i < nodes.Count; i++)
            {
                XmlNode styleNode = nodes[i];
                if (styleNode == null || styleNode.LocalName != "style")
                    continue;

                string name = OdfPackageUtility.GetAttributeByLocalName(styleNode, "name");
                string family = OdfPackageUtility.GetAttributeByLocalName(styleNode, "family");
                if (string.IsNullOrEmpty(name))
                    continue;

                if (family == "text")
                {
                    RunStyle style = new RunStyle();
                    XmlNode properties = FindChild(styleNode, "text-properties");
                    if (properties != null)
                    {
                        string font = OdfPackageUtility.GetAttributeByLocalName(properties, "font-family");
                        if (!string.IsNullOrEmpty(font))
                            style.FontFamily = font.Trim('\'', '"');
                        style.FontSize = ParsePointSize(
                            OdfPackageUtility.GetAttributeByLocalName(properties, "font-size"),
                            11f);
                        style.Bold = string.Equals(
                            OdfPackageUtility.GetAttributeByLocalName(properties, "font-weight"),
                            "bold",
                            StringComparison.OrdinalIgnoreCase);
                        style.Italic = string.Equals(
                            OdfPackageUtility.GetAttributeByLocalName(properties, "font-style"),
                            "italic",
                            StringComparison.OrdinalIgnoreCase);
                        string underline = OdfPackageUtility.GetAttributeByLocalName(properties, "text-underline-style");
                        style.Underline = !string.IsNullOrEmpty(underline) &&
                            !string.Equals(underline, "none", StringComparison.OrdinalIgnoreCase);
                        style.Color = NormalizeColor(
                            OdfPackageUtility.GetAttributeByLocalName(properties, "color"));
                    }
                    runStyles[name] = style;
                }
                else if (family == "paragraph")
                {
                    XmlNode properties = FindChild(styleNode, "paragraph-properties");
                    string alignment = OdfPackageUtility.GetAttributeByLocalName(properties, "text-align");
                    paraStyles[name] = ParseAlignment(alignment);
                }
            }
        }

        private static string ReadTitle(ZipArchive archive)
        {
            XmlDocument meta = OdfPackageUtility.LoadXml(archive, "meta.xml");
            XmlNode title = FindFirst(meta, "title");
            return title == null || string.IsNullOrEmpty(title.InnerText)
                ? "ODT Document"
                : title.InnerText;
        }

        private static XmlNode FindFirst(XmlDocument document, string localName)
        {
            if (document == null)
                return null;
            XmlNodeList nodes = document.GetElementsByTagName("*");
            for (int i = 0; i < nodes.Count; i++)
                if (nodes[i] != null && nodes[i].LocalName == localName)
                    return nodes[i];
            return null;
        }

        private static XmlNode FindChild(XmlNode parent, string localName)
        {
            if (parent == null)
                return null;
            for (int i = 0; i < parent.ChildNodes.Count; i++)
                if (parent.ChildNodes[i] != null && parent.ChildNodes[i].LocalName == localName)
                    return parent.ChildNodes[i];
            return null;
        }

        private static DocumentParagraphAlignment ParseAlignment(string value)
        {
            if (string.Equals(value, "center", StringComparison.OrdinalIgnoreCase))
                return DocumentParagraphAlignment.Center;
            if (string.Equals(value, "right", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(value, "end", StringComparison.OrdinalIgnoreCase))
                return DocumentParagraphAlignment.Right;
            if (string.Equals(value, "justify", StringComparison.OrdinalIgnoreCase))
                return DocumentParagraphAlignment.Justify;
            return DocumentParagraphAlignment.Left;
        }

        private static float ParsePointSize(string value, float fallback)
        {
            string text = (value ?? string.Empty).Trim();
            if (text.EndsWith("pt", StringComparison.OrdinalIgnoreCase))
                text = text.Substring(0, text.Length - 2);
            float parsed;
            return float.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out parsed)
                ? Math.Max(1f, Math.Min(400f, parsed))
                : fallback;
        }

        private static int ParseInt(string value, int fallback)
        {
            int parsed;
            return int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out parsed)
                ? parsed
                : fallback;
        }

        private static string NormalizeColor(string value)
        {
            string text = (value ?? string.Empty).Trim().TrimStart('#').ToUpperInvariant();
            int parsed;
            if (text.Length == 6 && int.TryParse(text, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out parsed))
                return text;
            return "20242A";
        }
    }

    internal static class OdtWriter
    {
        private sealed class RunStyleKey
        {
            public string FontFamily;
            public int SizeHundredths;
            public bool Bold;
            public bool Italic;
            public bool Underline;
            public string Color;

            public string Key
            {
                get
                {
                    return (FontFamily ?? string.Empty) + "|" +
                        SizeHundredths.ToString(CultureInfo.InvariantCulture) + "|" +
                        (Bold ? "1" : "0") + (Italic ? "1" : "0") + (Underline ? "1" : "0") + "|" + Color;
                }
            }
        }

        private sealed class StyleCatalog
        {
            public readonly List<RunStyleKey> RunStyles = new List<RunStyleKey>();
            public readonly Dictionary<string, int> RunStyleIds =
                new Dictionary<string, int>(StringComparer.Ordinal);
        }

        public static void Save(TextDocument document, string path)
        {
            if (document == null)
                throw new ArgumentNullException("document");
            if (string.IsNullOrEmpty(path))
                throw new ArgumentException("Destination path is required.", "path");

            string destination = Path.GetFullPath(path);
            if (!string.Equals(Path.GetExtension(destination), ".odt", StringComparison.OrdinalIgnoreCase))
                destination = Path.ChangeExtension(destination, "odt");

            string directory = Path.GetDirectoryName(destination);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);

            string stage = destination + ".writing";
            string backup = destination + ".backup";
            OdfPackageUtility.DeleteIfExists(stage);
            OdfPackageUtility.DeleteIfExists(backup);

            StyleCatalog catalog = BuildCatalog(document);

            try
            {
                using (FileStream file = new FileStream(stage, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.None))
                using (ZipArchive archive = new ZipArchive(file, ZipArchiveMode.Create, false))
                {
                    OdfPackageUtility.WriteTextEntry(
                        archive,
                        "mimetype",
                        OdfPackageUtility.TextMimeType,
                        CompressionLevel.NoCompression);
                    OdfPackageUtility.WriteTextEntry(
                        archive,
                        "content.xml",
                        BuildContentXml(document, catalog),
                        CompressionLevel.Optimal);
                    OdfPackageUtility.WriteTextEntry(
                        archive,
                        "styles.xml",
                        BuildStylesXml(),
                        CompressionLevel.Optimal);
                    OdfPackageUtility.WriteTextEntry(
                        archive,
                        "meta.xml",
                        OdfPackageUtility.BuildMetaXml(document.Title),
                        CompressionLevel.Optimal);

                    List<OdfManifestEntry> manifest = new List<OdfManifestEntry>();
                    manifest.Add(new OdfManifestEntry("content.xml", "text/xml"));
                    manifest.Add(new OdfManifestEntry("styles.xml", "text/xml"));
                    manifest.Add(new OdfManifestEntry("meta.xml", "text/xml"));
                    OdfPackageUtility.WriteTextEntry(
                        archive,
                        "META-INF/manifest.xml",
                        OdfPackageUtility.BuildManifest(OdfDocumentKind.Text, manifest),
                        CompressionLevel.Optimal);
                }

                OdfPackageUtility.ReplaceSafely(stage, destination, backup);
            }
            catch
            {
                OdfPackageUtility.DeleteIfExists(stage);
                throw;
            }
        }

        private static StyleCatalog BuildCatalog(TextDocument document)
        {
            StyleCatalog catalog = new StyleCatalog();

            for (int p = 0; p < document.Paragraphs.Count; p++)
            {
                DocumentParagraph paragraph = document.Paragraphs[p];
                if (paragraph == null)
                    continue;

                for (int r = 0; r < paragraph.Runs.Count; r++)
                {
                    DocumentTextRun run = paragraph.Runs[r];
                    if (run == null)
                        continue;

                    RunStyleKey key = CreateKey(run);
                    if (!catalog.RunStyleIds.ContainsKey(key.Key))
                    {
                        int id = catalog.RunStyles.Count;
                        catalog.RunStyleIds.Add(key.Key, id);
                        catalog.RunStyles.Add(key);
                    }
                }
            }

            if (catalog.RunStyles.Count == 0)
            {
                RunStyleKey fallback = CreateKey(new DocumentTextRun());
                catalog.RunStyleIds[fallback.Key] = 0;
                catalog.RunStyles.Add(fallback);
            }

            return catalog;
        }

        private static RunStyleKey CreateKey(DocumentTextRun run)
        {
            RunStyleKey key = new RunStyleKey();
            key.FontFamily = string.IsNullOrEmpty(run.FontFamily) ? "Arial" : run.FontFamily;
            key.SizeHundredths = Math.Max(100, Math.Min(40000, (int)Math.Round(run.FontSizePoints * 100f)));
            key.Bold = run.Bold;
            key.Italic = run.Italic;
            key.Underline = run.Underline;
            key.Color = NormalizeColor(run.ColorHex);
            return key;
        }

        private static string BuildContentXml(TextDocument document, StyleCatalog catalog)
        {
            StringBuilder xml = new StringBuilder();
            xml.Append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
            xml.Append("<office:document-content ");
            xml.Append("xmlns:office=\"urn:oasis:names:tc:opendocument:xmlns:office:1.0\" ");
            xml.Append("xmlns:text=\"urn:oasis:names:tc:opendocument:xmlns:text:1.0\" ");
            xml.Append("xmlns:style=\"urn:oasis:names:tc:opendocument:xmlns:style:1.0\" ");
            xml.Append("xmlns:fo=\"urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0\" ");
            xml.Append("office:version=\"1.3\">");
            xml.Append("<office:automatic-styles>");

            xml.Append(BuildParagraphStyle("P0", "start"));
            xml.Append(BuildParagraphStyle("P1", "center"));
            xml.Append(BuildParagraphStyle("P2", "end"));
            xml.Append(BuildParagraphStyle("P3", "justify"));

            for (int i = 0; i < catalog.RunStyles.Count; i++)
                xml.Append(BuildRunStyle(catalog.RunStyles[i], i));

            xml.Append("</office:automatic-styles><office:body><office:text>");

            for (int p = 0; p < document.Paragraphs.Count; p++)
            {
                DocumentParagraph paragraph = document.Paragraphs[p];
                if (paragraph == null)
                    continue;

                xml.Append("<text:p text:style-name=\"P");
                xml.Append(((int)paragraph.Alignment).ToString(CultureInfo.InvariantCulture));
                xml.Append("\">");

                if (paragraph.Runs.Count == 0)
                {
                    xml.Append("<text:span text:style-name=\"T0\"></text:span>");
                }
                else
                {
                    for (int r = 0; r < paragraph.Runs.Count; r++)
                    {
                        DocumentTextRun run = paragraph.Runs[r];
                        if (run == null)
                            continue;
                        RunStyleKey key = CreateKey(run);
                        int id;
                        if (!catalog.RunStyleIds.TryGetValue(key.Key, out id))
                            id = 0;
                        xml.Append("<text:span text:style-name=\"T");
                        xml.Append(id.ToString(CultureInfo.InvariantCulture));
                        xml.Append("\">");
                        AppendOdfText(xml, run.Text ?? string.Empty);
                        xml.Append("</text:span>");
                    }
                }

                xml.Append("</text:p>");
            }

            if (document.Paragraphs.Count == 0)
                xml.Append("<text:p text:style-name=\"P0\"/>");

            xml.Append("</office:text></office:body></office:document-content>");
            return xml.ToString();
        }

        private static string BuildParagraphStyle(string name, string alignment)
        {
            return "<style:style style:name=\"" + name +
                "\" style:family=\"paragraph\"><style:paragraph-properties fo:text-align=\"" +
                alignment + "\"/></style:style>";
        }

        private static string BuildRunStyle(RunStyleKey style, int id)
        {
            StringBuilder xml = new StringBuilder();
            xml.Append("<style:style style:name=\"T");
            xml.Append(id.ToString(CultureInfo.InvariantCulture));
            xml.Append("\" style:family=\"text\"><style:text-properties fo:font-family=\"");
            xml.Append(OdfPackageUtility.EscapeXml(style.FontFamily));
            xml.Append("\" fo:font-size=\"");
            xml.Append((style.SizeHundredths / 100f).ToString("0.##", CultureInfo.InvariantCulture));
            xml.Append("pt\" fo:color=\"#");
            xml.Append(style.Color);
            xml.Append("\"");
            if (style.Bold)
                xml.Append(" fo:font-weight=\"bold\"");
            if (style.Italic)
                xml.Append(" fo:font-style=\"italic\"");
            if (style.Underline)
                xml.Append(" style:text-underline-style=\"solid\" style:text-underline-width=\"auto\"");
            xml.Append("/></style:style>");
            return xml.ToString();
        }

        private static string BuildStylesXml()
        {
            return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<office:document-styles " +
                "xmlns:office=\"urn:oasis:names:tc:opendocument:xmlns:office:1.0\" " +
                "xmlns:style=\"urn:oasis:names:tc:opendocument:xmlns:style:1.0\" " +
                "xmlns:fo=\"urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0\" " +
                "office:version=\"1.3\">" +
                "<office:styles><style:default-style style:family=\"paragraph\">" +
                "<style:paragraph-properties fo:margin-top=\"0cm\" fo:margin-bottom=\"0.18cm\"/>" +
                "<style:text-properties fo:font-family=\"Arial\" fo:font-size=\"11pt\"/>" +
                "</style:default-style></office:styles>" +
                "</office:document-styles>";
        }

        private static void AppendOdfText(StringBuilder xml, string value)
        {
            string text = (value ?? string.Empty).Replace("\r\n", "\n").Replace('\r', '\n');
            StringBuilder plain = new StringBuilder();

            for (int i = 0; i < text.Length; i++)
            {
                char ch = text[i];
                if (ch == '\t' || ch == '\n')
                {
                    FlushPlain(xml, plain);
                    xml.Append(ch == '\t' ? "<text:tab/>" : "<text:line-break/>");
                    continue;
                }

                if (ch == ' ')
                {
                    int start = i;
                    while (i + 1 < text.Length && text[i + 1] == ' ')
                        i++;
                    int count = i - start + 1;
                    if (count == 1)
                    {
                        plain.Append(' ');
                    }
                    else
                    {
                        plain.Append(' ');
                        FlushPlain(xml, plain);
                        xml.Append("<text:s text:c=\"");
                        xml.Append((count - 1).ToString(CultureInfo.InvariantCulture));
                        xml.Append("\"/>");
                    }
                    continue;
                }

                plain.Append(ch);
            }

            FlushPlain(xml, plain);
        }

        private static void FlushPlain(StringBuilder xml, StringBuilder plain)
        {
            if (plain.Length == 0)
                return;
            xml.Append(OdfPackageUtility.EscapeXml(plain.ToString()));
            plain.Length = 0;
        }

        private static string NormalizeColor(string value)
        {
            string text = (value ?? string.Empty).Trim().TrimStart('#').ToUpperInvariant();
            int parsed;
            if (text.Length == 6 && int.TryParse(text, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out parsed))
                return text;
            return "20242A";
        }
    }
}
