using System;
using System.IO;
using System.Text;

namespace PptxViewer
{
    internal static class PdfExportDiagnostics
    {
        public static void CreateAndValidate(string outputDirectory)
        {
            if (string.IsNullOrEmpty(outputDirectory))
                outputDirectory = AppDomain.CurrentDomain.BaseDirectory;

            Directory.CreateDirectory(outputDirectory);

            string presentationPath = Path.Combine(outputDirectory, "TEST_PDF_PRESENTATION.pdf");
            string documentPath = Path.Combine(outputDirectory, "TEST_PDF_DOCUMENT.pdf");
            string spreadsheetPath = Path.Combine(outputDirectory, "TEST_PDF_SPREADSHEET.pdf");

            PresentationDocument presentation =
                PresentationDocument.CreateNew("PDF Presentation Test");
            PresentationSlide slide = presentation.AddSlide("Raster PDF Export");
            PresentationShape shape = slide.AddShape(PresentationShapeKind.RoundedRectangle);
            shape.X = 1371600;
            shape.Y = 2514600;
            shape.Width = 3657600;
            shape.Height = 1371600;
            shape.FillColorHex = "5B8CFF";
            PresentationTextBox box = slide.AddTextBox(
                "PDF export uses raster pages, so no font file is embedded into the PDF.");
            box.X = 5486400;
            box.Y = 2286000;
            box.Width = 5486400;
            box.Height = 1828800;
            box.FontSizePoints = 20f;
            box.Alignment = PresentationTextAlignment.Center;

            PdfExportService.ExportPresentation(presentation, presentationPath);

            TextDocument textDocument = TextDocument.CreateNew("PDF Text Document Test");
            DocumentParagraph first = textDocument.AddParagraph(
                "This page was generated by the project raster PDF exporter.");
            if (first.Runs.Count > 0)
            {
                first.Runs[0].Bold = true;
                first.Runs[0].FontSizePoints = 14f;
            }
            textDocument.AddParagraph(
                "The initial PDF path intentionally avoids embedding TTF/OTF data. A future vector/text PDF path must use FontLicenseService before embedding fonts.");
            PdfExportService.ExportTextDocument(textDocument, documentPath);

            SpreadsheetDocument workbook = SpreadsheetDocument.CreateNew("PDF Spreadsheet Test");
            SpreadsheetSheet sheet = workbook.Sheets[0];
            sheet.SetInput(1, 1, "Name");
            sheet.SetInput(1, 2, "Value");
            sheet.SetInput(2, 1, "Alpha");
            sheet.SetInput(2, 2, "123.5");
            sheet.SetInput(3, 1, "Formula storage");
            sheet.SetInput(3, 2, "=B2*2");
            PdfExportService.ExportSpreadsheet(workbook, spreadsheetPath);

            ValidatePdf(presentationPath);
            ValidatePdf(documentPath);
            ValidatePdf(spreadsheetPath);
        }

        private static void ValidatePdf(string path)
        {
            if (!File.Exists(path))
                throw new InvalidOperationException("PDF output was not created: " + path);

            FileInfo info = new FileInfo(path);
            if (info.Length < 512)
                throw new InvalidDataException("PDF output is unexpectedly small: " + path);

            byte[] data = File.ReadAllBytes(path);
            string header = Encoding.ASCII.GetString(data, 0, Math.Min(8, data.Length));
            if (!header.StartsWith("%PDF-1.", StringComparison.Ordinal))
                throw new InvalidDataException("PDF header is invalid: " + path);

            int tailLength = Math.Min(64, data.Length);
            string tail = Encoding.ASCII.GetString(
                data,
                data.Length - tailLength,
                tailLength);

            if (tail.IndexOf("%%EOF", StringComparison.Ordinal) < 0)
                throw new InvalidDataException("PDF EOF marker is missing: " + path);
        }
    }
}
