using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Text;
using System.Xml;
using System.Windows.Forms;

namespace PptxViewer
{
    internal sealed class PptxCompatibilityReport
    {
        public string FilePath { get; set; }
        public int SlideCount { get; set; }
        public bool IsPowerPointLiteGenerated { get; set; }
        public bool CanRoundTripSafely { get; set; }
        public bool HasCharts { get; set; }
        public bool HasSmartArt { get; set; }
        public bool HasMedia { get; set; }
        public bool HasEmbeddedObjects { get; set; }
        public bool HasNotes { get; set; }
        public bool HasComments { get; set; }
        public bool HasTransitionsOrAnimations { get; set; }
        public bool HasMacros { get; set; }
        public bool HasActiveX { get; set; }
        public bool HasCustomXml { get; set; }
        public string EditableReaderWarning { get; set; }
        public readonly List<string> UnknownPartExamples = new List<string>();

        public PptxCompatibilityReport()
        {
            FilePath = string.Empty;
            EditableReaderWarning = string.Empty;
        }

        public string ToDisplayText()
        {
            StringBuilder text = new StringBuilder();
            text.AppendLine("PPTX compatibility report");
            text.AppendLine("=========================");
            text.AppendLine();
            text.AppendLine("File: " + Path.GetFileName(FilePath));
            text.AppendLine("Slides: " + SlideCount.ToString());
            text.AppendLine(
                "Generated by current writer: " +
                (IsPowerPointLiteGenerated ? "Yes" : "No / unknown"));
            text.AppendLine(
                "Current experimental editor safe round-trip: " +
                (CanRoundTripSafely ? "YES" : "NO"));
            text.AppendLine();
            text.AppendLine("Detected content");
            text.AppendLine("----------------");
            AppendFlag(text, "Charts", HasCharts);
            AppendFlag(text, "SmartArt / diagram parts", HasSmartArt);
            AppendFlag(text, "Audio / video / media", HasMedia);
            AppendFlag(text, "Embedded objects", HasEmbeddedObjects);
            AppendFlag(text, "Speaker notes", HasNotes);
            AppendFlag(text, "Comments", HasComments);
            AppendFlag(text, "Transitions / animations", HasTransitionsOrAnimations);
            AppendFlag(text, "VBA macro project", HasMacros);
            AppendFlag(text, "ActiveX", HasActiveX);
            AppendFlag(text, "Custom XML", HasCustomXml);

            if (!string.IsNullOrEmpty(EditableReaderWarning))
            {
                text.AppendLine();
                text.AppendLine("Safe-edit guard");
                text.AppendLine("---------------");
                text.AppendLine(EditableReaderWarning);
            }

            if (UnknownPartExamples.Count > 0)
            {
                text.AppendLine();
                text.AppendLine("Additional package parts (sample)");
                text.AppendLine("---------------------------------");

                for (int i = 0; i < UnknownPartExamples.Count; i++)
                    text.AppendLine("- " + UnknownPartExamples[i]);
            }

            text.AppendLine();
            text.AppendLine(
                "This scan is read-only. It does not execute macros, ActiveX, embedded files, or media.");
            return text.ToString();
        }

        private static void AppendFlag(
            StringBuilder text,
            string label,
            bool value)
        {
            text.AppendLine((value ? "[detected] " : "[none]     ") + label);
        }
    }

    internal static class PptxCompatibilityAnalyzer
    {
        public static PptxCompatibilityReport Analyze(string path)
        {
            if (string.IsNullOrEmpty(path) || !File.Exists(path))
                throw new FileNotFoundException("PPTX file was not found.", path);

            PptxCompatibilityReport report = new PptxCompatibilityReport();
            report.FilePath = Path.GetFullPath(path);

            using (ZipArchive archive = ZipFile.OpenRead(path))
            {
                for (int i = 0; i < archive.Entries.Count; i++)
                {
                    ZipArchiveEntry entry = archive.Entries[i];
                    string name = entry.FullName.Replace('\\', '/');
                    string lower = name.ToLowerInvariant();

                    if (lower.StartsWith("ppt/slides/slide") &&
                        lower.EndsWith(".xml") &&
                        lower.IndexOf("/_rels/", StringComparison.Ordinal) < 0)
                    {
                        report.SlideCount++;
                        if (SlideHasTiming(entry))
                            report.HasTransitionsOrAnimations = true;
                    }

                    if (lower.StartsWith("ppt/charts/"))
                        report.HasCharts = true;
                    else if (lower.StartsWith("ppt/diagrams/"))
                        report.HasSmartArt = true;
                    else if (lower.StartsWith("ppt/media/"))
                        report.HasMedia = true;
                    else if (lower.StartsWith("ppt/embeddings/"))
                        report.HasEmbeddedObjects = true;
                    else if (lower.StartsWith("ppt/notesslides/"))
                        report.HasNotes = true;
                    else if (lower.StartsWith("ppt/comments/") ||
                             lower.IndexOf("commentauthors", StringComparison.Ordinal) >= 0)
                        report.HasComments = true;
                    else if (lower.EndsWith("vbaproject.bin"))
                        report.HasMacros = true;
                    else if (lower.StartsWith("ppt/activex/"))
                        report.HasActiveX = true;
                    else if (lower.StartsWith("customxml/"))
                        report.HasCustomXml = true;

                    if (!IsKnownCorePart(lower) &&
                        report.UnknownPartExamples.Count < 12)
                    {
                        report.UnknownPartExamples.Add(name);
                    }
                }
            }

            try
            {
                PptxEditableLoadResult editable =
                    PptxEditableReader.Read(path);

                if (editable != null)
                {
                    report.IsPowerPointLiteGenerated =
                        editable.IsPowerPointLiteGenerated;
                    report.CanRoundTripSafely =
                        editable.CanRoundTripSafely;
                    report.EditableReaderWarning =
                        editable.Warning ?? string.Empty;
                }
            }
            catch (Exception ex)
            {
                report.CanRoundTripSafely = false;
                report.EditableReaderWarning =
                    "Editable-reader validation failed: " + ex.Message;
            }

            return report;
        }

        private static bool SlideHasTiming(ZipArchiveEntry entry)
        {
            if (entry == null)
                return false;

            try
            {
                XmlDocument document = new XmlDocument();
                using (Stream stream = entry.Open())
                    document.Load(stream);

                return HasElement(document.DocumentElement, "timing") ||
                       HasElement(document.DocumentElement, "transition");
            }
            catch
            {
                return false;
            }
        }

        private static bool HasElement(XmlNode node, string localName)
        {
            if (node == null)
                return false;

            if (node.LocalName == localName)
                return true;

            for (int i = 0; i < node.ChildNodes.Count; i++)
            {
                if (HasElement(node.ChildNodes[i], localName))
                    return true;
            }

            return false;
        }

        private static bool IsKnownCorePart(string lower)
        {
            if (string.IsNullOrEmpty(lower))
                return true;

            return lower == "[content_types].xml" ||
                   lower == "_rels/.rels" ||
                   lower == "docprops/core.xml" ||
                   lower == "docprops/app.xml" ||
                   lower == "ppt/presentation.xml" ||
                   lower == "ppt/_rels/presentation.xml.rels" ||
                   lower.StartsWith("ppt/slides/") ||
                   lower.StartsWith("ppt/slidelayouts/") ||
                   lower.StartsWith("ppt/slidemasters/") ||
                   lower.StartsWith("ppt/theme/") ||
                   lower.StartsWith("ppt/media/");
        }
    }

    internal sealed class PptxCompatibilityReportForm : Form
    {
        public PptxCompatibilityReportForm(PptxCompatibilityReport report)
        {
            if (report == null)
                throw new ArgumentNullException("report");

            Text = "PPTX Compatibility";
            StartPosition = FormStartPosition.CenterParent;
            Width = 760;
            Height = 620;
            MinimumSize = new System.Drawing.Size(560, 420);
            BackColor = ApplicationTheme.Window;
            ForeColor = ApplicationTheme.PrimaryText;
            Font = new System.Drawing.Font("Segoe UI", 9f);

            RichTextBox output = new RichTextBox();
            output.Dock = DockStyle.Fill;
            output.ReadOnly = true;
            output.BorderStyle = BorderStyle.None;
            output.BackColor = System.Drawing.Color.FromArgb(245, 246, 248);
            output.ForeColor = System.Drawing.Color.FromArgb(28, 31, 36);
            output.Font = new System.Drawing.Font("Consolas", 9.5f);
            output.Text = report.ToDisplayText();
            Controls.Add(output);

            Panel bottom = new Panel();
            bottom.Dock = DockStyle.Bottom;
            bottom.Height = 48;
            bottom.Padding = new Padding(8);
            bottom.BackColor = ApplicationTheme.Toolbar;
            Controls.Add(bottom);
            bottom.BringToFront();

            Button close = new Button();
            close.Text = "Close";
            close.Width = 82;
            close.Height = 32;
            close.Left = 8;
            close.Top = 8;
            close.DialogResult = DialogResult.OK;
            ApplicationTheme.ApplyButton(close);
            bottom.Controls.Add(close);

            AcceptButton = close;
            CancelButton = close;
        }
    }
}
