using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Text;
using System.Xml;

namespace PptxViewer
{
    internal sealed class PptxEditableLoadResult
    {
        public PresentationDocument Document { get; set; }
        public bool IsPowerPointLiteGenerated { get; set; }
        public bool HasUnsupportedContent { get; set; }
        public bool CanRoundTripSafely { get; set; }
        public string Warning { get; set; }

        public PptxEditableLoadResult()
        {
            Warning = string.Empty;
        }
    }

    internal static class PptxEditableReader
    {
        private const string SlideRelationshipSuffix = "/slide";
        private const string SlideLayoutRelationshipSuffix = "/slideLayout";
        private const string ImageRelationshipSuffix = "/image";

        public static PptxEditableLoadResult Read(string path)
        {
            if (string.IsNullOrEmpty(path) || !File.Exists(path))
                throw new FileNotFoundException("PPTX file was not found.", path);

            PptxEditableLoadResult result = new PptxEditableLoadResult();

            using (ZipArchive archive = ZipFile.OpenRead(path))
            {
                result.IsPowerPointLiteGenerated = IsGeneratedByPowerPointLite(archive);

                XmlDocument presentation =
                    OpcPackageUtility.ReadXmlPart(archive, "ppt/presentation.xml");

                if (presentation == null)
                    throw new InvalidDataException("ppt/presentation.xml is missing or invalid.");

                PresentationDocument document = new PresentationDocument();
                document.Title = ReadCoreTitle(archive);

                ReadSlideSize(presentation, document);

                List<OpcRelationship> relationships =
                    OpcPackageUtility.ReadRelationships(archive, "ppt/presentation.xml");

                Dictionary<string, OpcRelationship> byId =
                    new Dictionary<string, OpcRelationship>(StringComparer.Ordinal);

                for (int i = 0; i < relationships.Count; i++)
                {
                    OpcRelationship relationship = relationships[i];
                    if (!string.IsNullOrEmpty(relationship.Id))
                        byId[relationship.Id] = relationship;
                }

                XmlNode slideIdList = FindFirst(presentation.DocumentElement, "sldIdLst");

                if (slideIdList == null)
                    throw new InvalidDataException("Presentation does not contain a slide list.");

                for (int i = 0; i < slideIdList.ChildNodes.Count; i++)
                {
                    XmlNode slideId = slideIdList.ChildNodes[i];
                    if (slideId.LocalName != "sldId")
                        continue;

                    string relationshipId = GetRelationshipReference(slideId, "id");
                    OpcRelationship relationship;

                    if (string.IsNullOrEmpty(relationshipId) ||
                        !byId.TryGetValue(relationshipId, out relationship) ||
                        relationship == null ||
                        relationship.IsExternal ||
                        !relationship.Type.EndsWith(SlideRelationshipSuffix, StringComparison.Ordinal))
                    {
                        continue;
                    }

                    XmlDocument slideDocument =
                        OpcPackageUtility.ReadXmlPart(archive, relationship.ResolvedPart);

                    if (slideDocument == null)
                        continue;

                    PresentationSlide slide = ReadSlide(
                        archive,
                        relationship.ResolvedPart,
                        slideDocument,
                        result);
                    document.Slides.Add(slide);
                }

                if (document.Slides.Count == 0)
                    document.AddSlide();

                result.Document = document;
                result.CanRoundTripSafely =
                    result.IsPowerPointLiteGenerated &&
                    !result.HasUnsupportedContent;

                if (!result.CanRoundTripSafely)
                {
                    result.Warning = result.IsPowerPointLiteGenerated
                        ? "This presentation contains content not yet represented by the editable model. Saving it through the experimental editor could lose unsupported parts."
                        : "This file was not generated by the current PowerPointLite writer. Open it in viewer mode until unknown-part preservation is implemented.";
                }
            }

            return result;
        }

        private static PresentationSlide ReadSlide(
            ZipArchive archive,
            string slidePart,
            XmlDocument document,
            PptxEditableLoadResult result)
        {
            PresentationSlide slide = new PresentationSlide();
            XmlNode commonSlideData = FindFirst(document.DocumentElement, "cSld");

            if (commonSlideData != null)
            {
                string name = GetAttribute(commonSlideData, "name");
                if (!string.IsNullOrEmpty(name))
                    slide.Name = name;
            }

            List<OpcRelationship> relationships =
                OpcPackageUtility.ReadRelationships(archive, slidePart);
            Dictionary<string, OpcRelationship> byId =
                new Dictionary<string, OpcRelationship>(StringComparer.Ordinal);

            for (int r = 0; r < relationships.Count; r++)
            {
                OpcRelationship relationship = relationships[r];
                if (!string.IsNullOrEmpty(relationship.Id))
                    byId[relationship.Id] = relationship;

                if (relationship == null || relationship.IsExternal)
                {
                    result.HasUnsupportedContent = true;
                    continue;
                }

                bool supportedRelationship =
                    relationship.Type.EndsWith(SlideLayoutRelationshipSuffix, StringComparison.Ordinal) ||
                    relationship.Type.EndsWith(ImageRelationshipSuffix, StringComparison.Ordinal);

                if (!supportedRelationship)
                    result.HasUnsupportedContent = true;
            }

            XmlNode shapeTree = FindFirst(commonSlideData, "spTree");
            if (shapeTree == null)
                return slide;

            for (int i = 0; i < shapeTree.ChildNodes.Count; i++)
            {
                XmlNode node = shapeTree.ChildNodes[i];

                if (node.LocalName == "sp")
                {
                    if (FindFirst(node, "txBody") != null)
                    {
                        PresentationTextBox box = ReadTextBox(node);
                        if (box != null)
                        {
                            slide.TextBoxes.Add(box);
                            slide.RegisterObjectOrder(
                                PresentationLayerKind.TextBox,
                                slide.TextBoxes.Count - 1);
                        }
                        else
                            result.HasUnsupportedContent = true;
                    }
                    else
                    {
                        PresentationShape shape = ReadShape(node);
                        if (shape != null)
                        {
                            slide.Shapes.Add(shape);
                            slide.RegisterObjectOrder(
                                PresentationLayerKind.Shape,
                                slide.Shapes.Count - 1);
                        }
                        else
                            result.HasUnsupportedContent = true;
                    }
                }
                else if (node.LocalName == "pic")
                {
                    PresentationImage image = ReadImage(
                        archive,
                        node,
                        byId);

                    if (image != null)
                    {
                        slide.Images.Add(image);
                        slide.RegisterObjectOrder(
                            PresentationLayerKind.Image,
                            slide.Images.Count - 1);
                    }
                    else
                        result.HasUnsupportedContent = true;
                }
                else if (node.LocalName == "graphicFrame")
                {
                    PresentationTable table = PptxTableReader.Read(node);

                    if (table != null)
                    {
                        slide.Tables.Add(table);
                        slide.RegisterObjectOrder(
                            PresentationLayerKind.Table,
                            slide.Tables.Count - 1);
                    }
                    else
                        result.HasUnsupportedContent = true;
                }
                else if (node.LocalName != "nvGrpSpPr" &&
                         node.LocalName != "grpSpPr")
                {
                    result.HasUnsupportedContent = true;
                }
            }

            if (FindFirst(document.DocumentElement, "timing") != null ||
                FindFirst(document.DocumentElement, "transition") != null)
            {
                result.HasUnsupportedContent = true;
            }

            return slide;
        }

        private static PresentationTextBox ReadTextBox(XmlNode shape)
        {
            XmlNode textBody = FindFirst(shape, "txBody");
            if (textBody == null)
                return null;

            PresentationTextBox box = new PresentationTextBox();

            XmlNode nonVisual = FindFirst(shape, "cNvPr");
            string name = GetAttribute(nonVisual, "name");
            if (!string.IsNullOrEmpty(name))
                box.Name = name;

            ReadTransform(shape, box);
            box.Text = ReadText(textBody);

            XmlNode firstParagraphProperties = FindFirst(textBody, "pPr");
            string alignment = GetAttribute(firstParagraphProperties, "algn");

            if (alignment == "ctr")
                box.Alignment = PresentationTextAlignment.Center;
            else if (alignment == "r")
                box.Alignment = PresentationTextAlignment.Right;
            else
                box.Alignment = PresentationTextAlignment.Left;

            XmlNode runProperties = FindFirst(textBody, "rPr");
            if (runProperties == null)
                runProperties = FindFirst(textBody, "endParaRPr");

            int sizeHundredths = GetIntAttribute(runProperties, "sz", 2000);
            box.FontSizePoints = Math.Max(1f, sizeHundredths / 100f);
            box.Bold = IsTrue(GetAttribute(runProperties, "b"));
            box.Italic = IsTrue(GetAttribute(runProperties, "i"));

            XmlNode latin = FindFirst(runProperties, "latin");
            string typeface = GetAttribute(latin, "typeface");
            if (!string.IsNullOrEmpty(typeface))
                box.FontFamily = typeface;

            XmlNode color = FindFirst(runProperties, "srgbClr");
            string colorValue = GetAttribute(color, "val");
            if (!string.IsNullOrEmpty(colorValue))
                box.ColorHex = colorValue;

            return box;
        }

        private static PresentationShape ReadShape(XmlNode shapeNode)
        {
            XmlNode shapeProperties = FindFirst(shapeNode, "spPr");
            XmlNode geometry = FindFirst(shapeProperties, "prstGeom");
            string preset = GetAttribute(geometry, "prst");
            PresentationShapeKind kind;

            if (preset == "rect")
                kind = PresentationShapeKind.Rectangle;
            else if (preset == "roundRect")
                kind = PresentationShapeKind.RoundedRectangle;
            else if (preset == "ellipse")
                kind = PresentationShapeKind.Ellipse;
            else if (preset == "triangle")
                kind = PresentationShapeKind.Triangle;
            else if (preset == "diamond")
                kind = PresentationShapeKind.Diamond;
            else
                return null;

            PresentationShape shape = new PresentationShape();
            shape.Kind = kind;

            XmlNode nonVisual = FindFirst(shapeNode, "cNvPr");
            string name = GetAttribute(nonVisual, "name");
            if (!string.IsNullOrEmpty(name))
                shape.Name = name;

            ReadTransform(shapeNode, shape);

            XmlNode fill = FindFirst(shapeProperties, "solidFill");
            XmlNode fillColor = FindFirst(fill, "srgbClr");
            string fillValue = GetAttribute(fillColor, "val");
            if (!string.IsNullOrEmpty(fillValue))
                shape.FillColorHex = fillValue;

            XmlNode line = FindFirst(shapeProperties, "ln");
            XmlNode lineColor = FindFirst(line, "srgbClr");
            string lineValue = GetAttribute(lineColor, "val");
            if (!string.IsNullOrEmpty(lineValue))
                shape.LineColorHex = lineValue;

            long lineWidth = GetLongAttribute(line, "w", 15875L);
            shape.LineWidthPoints = Math.Max(0.25f, lineWidth / 12700f);
            return shape;
        }

        private static PresentationImage ReadImage(
            ZipArchive archive,
            XmlNode pictureNode,
            Dictionary<string, OpcRelationship> relationships)
        {
            XmlNode blip = FindFirst(pictureNode, "blip");
            string relationshipId = GetRelationshipReference(blip, "embed");
            OpcRelationship relationship;

            if (string.IsNullOrEmpty(relationshipId) ||
                relationships == null ||
                !relationships.TryGetValue(relationshipId, out relationship) ||
                relationship == null ||
                relationship.IsExternal ||
                !relationship.Type.EndsWith(ImageRelationshipSuffix, StringComparison.Ordinal))
            {
                return null;
            }

            ZipArchiveEntry entry = archive.GetEntry(
                OpcPackageUtility.NormalizePartName(relationship.ResolvedPart));
            if (entry == null)
                return null;

            byte[] data;
            using (Stream input = entry.Open())
            using (MemoryStream output = new MemoryStream())
            {
                input.CopyTo(output);
                data = output.ToArray();
            }

            string extension = Path.GetExtension(relationship.ResolvedPart)
                .TrimStart('.')
                .ToLowerInvariant();
            string contentType = ImageContentType(extension);

            if (string.IsNullOrEmpty(contentType))
                return null;

            PresentationImage image = new PresentationImage();
            image.Data = data;
            image.Extension = extension;
            image.ContentType = contentType;

            XmlNode nonVisual = FindFirst(pictureNode, "cNvPr");
            string name = GetAttribute(nonVisual, "name");
            if (!string.IsNullOrEmpty(name))
                image.Name = name;

            ReadTransform(pictureNode, image);

            XmlNode sourceRectangle =
                FindFirst(
                    pictureNode,
                    "srcRect");

            if (sourceRectangle != null)
            {
                image.CropLeft =
                    PresentationRenderPrimitives.ClampCropValue(
                        (int)GetLongAttribute(
                            sourceRectangle,
                            "l",
                            0L));
                image.CropTop =
                    PresentationRenderPrimitives.ClampCropValue(
                        (int)GetLongAttribute(
                            sourceRectangle,
                            "t",
                            0L));
                image.CropRight =
                    PresentationRenderPrimitives.ClampCropValue(
                        (int)GetLongAttribute(
                            sourceRectangle,
                            "r",
                            0L));
                image.CropBottom =
                    PresentationRenderPrimitives.ClampCropValue(
                        (int)GetLongAttribute(
                            sourceRectangle,
                            "b",
                            0L));
            }

            return image;
        }

        private static void ReadTransform(XmlNode node, PresentationTextBox box)
        {
            XmlNode transform = FindFirst(node, "xfrm");
            XmlNode offset = FindFirst(transform, "off");
            XmlNode extent = FindFirst(transform, "ext");
            box.X = GetLongAttribute(offset, "x", box.X);
            box.Y = GetLongAttribute(offset, "y", box.Y);
            box.Width = Math.Max(1L, GetLongAttribute(extent, "cx", box.Width));
            box.Height = Math.Max(1L, GetLongAttribute(extent, "cy", box.Height));
        }

        private static void ReadTransform(XmlNode node, PresentationShape shape)
        {
            XmlNode transform = FindFirst(node, "xfrm");
            XmlNode offset = FindFirst(transform, "off");
            XmlNode extent = FindFirst(transform, "ext");
            shape.X = GetLongAttribute(offset, "x", shape.X);
            shape.Y = GetLongAttribute(offset, "y", shape.Y);
            shape.Width = Math.Max(1L, GetLongAttribute(extent, "cx", shape.Width));
            shape.Height = Math.Max(1L, GetLongAttribute(extent, "cy", shape.Height));
        }

        private static void ReadTransform(XmlNode node, PresentationImage image)
        {
            XmlNode transform = FindFirst(node, "xfrm");
            XmlNode offset = FindFirst(transform, "off");
            XmlNode extent = FindFirst(transform, "ext");
            image.X = GetLongAttribute(offset, "x", image.X);
            image.Y = GetLongAttribute(offset, "y", image.Y);
            image.Width = Math.Max(1L, GetLongAttribute(extent, "cx", image.Width));
            image.Height = Math.Max(1L, GetLongAttribute(extent, "cy", image.Height));
        }

        private static string ImageContentType(string extension)
        {
            if (extension == "png")
                return "image/png";
            if (extension == "jpg" || extension == "jpeg")
                return "image/jpeg";
            if (extension == "gif")
                return "image/gif";
            if (extension == "bmp")
                return "image/bmp";
            return string.Empty;
        }

        private static string ReadText(XmlNode textBody)
        {
            StringBuilder result = new StringBuilder();
            List<XmlNode> paragraphs = FindAll(textBody, "p");

            for (int i = 0; i < paragraphs.Count; i++)
            {
                if (i > 0)
                    result.AppendLine();

                List<XmlNode> textNodes = FindAll(paragraphs[i], "t");

                for (int t = 0; t < textNodes.Count; t++)
                    result.Append(textNodes[t].InnerText);
            }

            return result.ToString();
        }

        private static void ReadSlideSize(
            XmlDocument presentation,
            PresentationDocument document)
        {
            XmlNode size = FindFirst(presentation.DocumentElement, "sldSz");
            document.WidthEmu = Math.Max(
                1L,
                GetLongAttribute(size, "cx", PresentationDocument.DefaultWidthEmu));
            document.HeightEmu = Math.Max(
                1L,
                GetLongAttribute(size, "cy", PresentationDocument.DefaultHeightEmu));
        }

        private static bool IsGeneratedByPowerPointLite(ZipArchive archive)
        {
            XmlDocument core = OpcPackageUtility.ReadXmlPart(archive, "docProps/core.xml");
            if (core == null)
                return false;

            XmlNode creator = FindFirst(core.DocumentElement, "creator");
            XmlNode modifiedBy = FindFirst(core.DocumentElement, "lastModifiedBy");

            return ContainsPowerPointLite(creator) || ContainsPowerPointLite(modifiedBy);
        }

        private static string ReadCoreTitle(ZipArchive archive)
        {
            XmlDocument core = OpcPackageUtility.ReadXmlPart(archive, "docProps/core.xml");
            XmlNode title = core == null ? null : FindFirst(core.DocumentElement, "title");
            return title == null || string.IsNullOrEmpty(title.InnerText)
                ? "Presentation"
                : title.InnerText;
        }

        private static bool ContainsPowerPointLite(XmlNode node)
        {
            return node != null &&
                node.InnerText.IndexOf("PowerPointLite", StringComparison.OrdinalIgnoreCase) >= 0;
        }

        private static bool IsTrue(string value)
        {
            return value == "1" ||
                string.Equals(value, "true", StringComparison.OrdinalIgnoreCase);
        }

        private static string GetRelationshipReference(XmlNode node, string localName)
        {
            if (node == null || node.Attributes == null)
                return string.Empty;

            for (int i = 0; i < node.Attributes.Count; i++)
            {
                XmlAttribute attribute = node.Attributes[i];

                if (attribute.LocalName == localName &&
                    (attribute.Prefix == "r" ||
                     attribute.NamespaceURI.IndexOf("relationships", StringComparison.OrdinalIgnoreCase) >= 0))
                {
                    return attribute.Value;
                }
            }

            return string.Empty;
        }

        private static string GetAttribute(XmlNode node, string name)
        {
            if (node == null || node.Attributes == null)
                return string.Empty;

            XmlAttribute direct = node.Attributes[name];
            if (direct != null)
                return direct.Value;

            for (int i = 0; i < node.Attributes.Count; i++)
            {
                if (node.Attributes[i].LocalName == name)
                    return node.Attributes[i].Value;
            }

            return string.Empty;
        }

        private static long GetLongAttribute(
            XmlNode node,
            string name,
            long fallback)
        {
            long value;
            return long.TryParse(GetAttribute(node, name), out value)
                ? value
                : fallback;
        }

        private static int GetIntAttribute(
            XmlNode node,
            string name,
            int fallback)
        {
            int value;
            return int.TryParse(GetAttribute(node, name), out value)
                ? value
                : fallback;
        }

        private static XmlNode FindFirst(XmlNode node, string localName)
        {
            if (node == null)
                return null;

            if (node.LocalName == localName)
                return node;

            for (int i = 0; i < node.ChildNodes.Count; i++)
            {
                XmlNode found = FindFirst(node.ChildNodes[i], localName);
                if (found != null)
                    return found;
            }

            return null;
        }

        private static List<XmlNode> FindAll(XmlNode node, string localName)
        {
            List<XmlNode> result = new List<XmlNode>();
            AddMatches(node, localName, result);
            return result;
        }

        private static void AddMatches(
            XmlNode node,
            string localName,
            List<XmlNode> result)
        {
            if (node == null)
                return;

            if (node.LocalName == localName)
                result.Add(node);

            for (int i = 0; i < node.ChildNodes.Count; i++)
                AddMatches(node.ChildNodes[i], localName, result);
        }
    }
}
